"""
2nd Grade Grammar Lessons - 40 lessons covering:
- Complete vs. incomplete sentences
- Common vs. proper nouns
- Past, present, future tense
- Singular and plural nouns
- Articles: a, an, the
- Contractions
- Pronoun-antecedent agreement
- Adverbs
"""

LESSONS_BASELINE_10 = [
    {
        "title": "Complete vs. Incomplete Sentences",
        "concept": "A complete sentence has a subject and predicate and makes sense. A fragment is missing part.",
        "sentences": [
            "the dog barks loud",
            "the girl runs fast",
            "the sun shines bright",
            "the bird builds nest",
            "the cat catches mouse",
            "the bear catches fish",
            "the frog jumps high",
            "the fish swims deep",
            "the bee collects pollen",
            "the snake sheds skin",
        ],
        "practice": "Write C if complete, I if incomplete: The boy ___. / Runs fast ___. / She reads ___. / Are happy ___.",
    },
    {
        "title": "Common vs. Proper Nouns",
        "concept": "Common nouns name general things. Proper nouns name specific people, places, and need capitals.",
        "sentences": [
            "city is general but new york city is proper",
            "state is general but california is proper",
            "river is general but amazon river is proper",
            "country is general but brazil is proper",
            "ocean is general but pacific ocean is proper",
            "teacher is common but mrs smith is proper",
            "friend is common but emily is proper",
            "school is common but lincoln elementary is proper",
            "park is common but central park is proper",
            "book is common but harry potter is proper",
        ],
        "practice": "Label each C for common or P for proper: ___ dog / ___ monday / ___ girl / ___ europe",
    },
    {
        "title": "Past Tense: Adding Ed",
        "concept": "Most verbs add ED to show something already happened.",
        "sentences": [
            "walk becomes walked",
            "play becomes played",
            "jump becomes jumped",
            "talk becomes talked",
            "learn becomes learned",
            "help becomes helped",
            "paint becomes painted",
            "bake becomes baked",
            "visit becomes visited",
            "start becomes started",
        ],
        "practice": "Change to past: today i walk / yesterday i ___",
    },
    {
        "title": "Past Tense: Irregular Verbs",
        "concept": "Some verbs change completely, not by adding ED.",
        "sentences": [
            "go becomes went",
            "see becomes saw",
            "come becomes came",
            "eat becomes ate",
            "drink becomes drank",
            "run becomes ran",
            "swim becomes swam",
            "write becomes wrote",
            "read becomes read",
            "sing becomes sang",
        ],
        "practice": "Write the past tense: go -> ___ / see -> ___ / eat -> ___",
    },
    {
        "title": "Present Tense",
        "concept": "Present tense tells what happens now. For he/she/it, add s or es.",
        "sentences": [
            "i walk to school",
            "she walks to school",
            "they play in the park",
            "he plays soccer",
            "it barks loud",
            "the bird sings beautiful",
            "she catches the ball",
            "he watches the game",
            "the cat purrs soft",
            "the dog wags tail",
        ],
        "practice": "Fix the verb: She walk to school. / He play games. / It bark loud.",
    },
    {
        "title": "Future Tense: Will",
        "concept": "Future tense tells what will happen. Use WILL before the verb.",
        "sentences": [
            "i will go to school tomorrow",
            "she will visit her grandmother",
            "they will play outside",
            "we will have a party",
            "it will rain later",
            "he will finish his homework",
            "the sun will set tonight",
            "she will read a book",
            "they will learn math",
            "we will go to the zoo",
        ],
        "practice": "Write future tense: I ___ (go) to school tomorrow. / She ___ (visit) grandma.",
    },
    {
        "title": "Singular and Plural Nouns",
        "concept": "Singular means one. Plural means more than one. Most add S.",
        "sentences": [
            "one cat but two cats",
            "one dog but three dogs",
            "one book but many books",
            "one chair but five chairs",
            "one apple but four apples",
            "one baby but two babies",
            "one box but six boxes",
            "one bus but three buses",
            "one country but many countries",
            "one church but four churches",
        ],
        "practice": "Make plural: one mouse -> two ___ / one leaf -> many ___ / one potato -> five ___",
    },
    {
        "title": "Irregular Plurals",
        "concept": "Some nouns change completely for plural.",
        "sentences": [
            "one child becomes many children",
            "one man becomes many men",
            "one woman becomes many women",
            "one foot becomes many feet",
            "one tooth becomes many teeth",
            "one mouse becomes many mice",
            "one goose becomes many geese",
            "one person becomes many people",
            "one ox becomes many oxen",
            "one sheep becomes many sheep",
        ],
        "practice": "Write the plural: one child -> ___ / one foot -> ___ / one mouse -> ___",
    },
    {
        "title": "Articles: A, An, The",
        "concept": "A and AN are indefinite articles (one of many). THE is definite (specific one). Use A before consonant sounds, AN before vowel sounds.",
        "sentences": [
            "a dog barked",
            "an elephant is big",
            "the dog is mine",
            "an apple a day",
            "a university is a school",
            "an hour is long",
            "the sun is bright",
            "a book on the table",
            "an ice cream cone",
            "the moon at night",
        ],
        "practice": "Fill in a, an, or the: ___ dog ran away. / ___ dogs ran away. / ___ dog is mine.",
    },
    {
        "title": "Contractions with Not",
        "concept": "When we add NOT, we can contract it with IS, ARE, DO, or DOES using an apostrophe.",
        "sentences": [
            "is not becomes isn't",
            "are not becomes aren't",
            "do not becomes don't",
            "does not becomes doesn't",
            "was not becomes wasn't",
            "were not becomes weren't",
            "cannot becomes can't",
            "will not becomes won't",
            "should not becomes shouldn't",
            "would not becomes wouldn't",
        ],
        "practice": "Make contractions: is not -> ___ / do not -> ___ / will not -> ___",
    },
    {
        "title": "Contractions with Pronouns",
        "concept": "Pronouns join with IS, ARE, AM, HAVE, WILL, and WOULD to make contractions.",
        "sentences": [
            "i am becomes i'm",
            "you are becomes you're",
            "he is becomes he's",
            "she is becomes she's",
            "it is becomes it's",
            "we are becomes we're",
            "they are becomes they're",
            "i have becomes i've",
            "we will becomes we'll",
            "they would becomes they'd",
        ],
        "practice": "Make contractions: I am happy -> ___ happy. / She is here -> ___ here. / We will go -> ___ go.",
    },
    {
        "title": "Pronoun Reference",
        "concept": "Pronouns must match the nouns they replace. He goes with boy. She goes with girl.",
        "sentences": [
            "the boy runs fast he runs fast",
            "the girl reads a book she reads a book",
            "the dog barks it barks loud",
            "the children play they play together",
            "mary lost her book she lost her book",
            "tom found his ball he found his ball",
            "the cat licked its paw it licked its paw",
            "birds build nests they build nests",
            "the teacher helps us she helps us",
            "my mom gave me a gift she gave me a gift",
        ],
        "practice": "Replace with pronoun: The boy ran. He ran. / The girl read. ___ read. / The dogs played. ___ played.",
    },
    {
        "title": "Adverbs: How, When, Where",
        "concept": "Adverbs tell more about verbs. They tell HOW, WHEN, or WHERE something happens.",
        "sentences": [
            "she sings beautifully how she sings",
            "he ran quickly how he ran",
            "they arrived early when they arrived",
            "we stayed there where we stayed",
            "the bird sings loudly how it sings",
            "she will come tomorrow when she will come",
            "look outside where to look",
            "he reads here where he reads",
            "they left yesterday when they left",
        ],
        "practice": "Identify the adverb and what it tells: She runs fast. / They arrived early. / We stayed here.",
    },
    {
        "title": "Adverbs Tell How: Carefully, Quickly, Slowly",
        "concept": "Adverbs that tell HOW modify verbs.",
        "sentences": [
            "she writes carefully",
            "he runs quickly",
            "the turtle moves slowly",
            "please listen carefully",
            "the baby sleeps peacefully",
            "the artist draws neatly",
            "the chef cooks skillfully",
            "students work quietly",
            "the fire burns brightly",
            "the rain falls softly",
        ],
        "practice": "Add an adverb: She draws ___. / He runs ___. / The bell rings ___.",
    },
    {
        "title": "Using Because",
        "concept": "Because shows WHY something happens. It joins two ideas.",
        "sentences": [
            "she studied because she wanted to pass",
            "the dog barked because it saw a stranger",
            "he was tired because he stayed up late",
            "plants grow because they get sunlight",
            "the cat hid because it was scared",
            "she smiled because she was happy",
            "the roads were wet because it rained",
            "he ate because he was hungry",
            "they celebrated because they won",
            "the class was quiet because the teacher was strict",
        ],
        "practice": "Join with because: It rained. The ground was wet. -> It rained because ___.",
    },
]


LESSONS_FULL_40 = LESSONS_BASELINE_10 + [
    {
        "title": "Using When",
        "concept": "When tells WHEN something happens. It joins two ideas about time.",
        "sentences": [
            "when the bell rings we line up",
            "she reads when she is tired",
            "the flowers bloom when spring comes",
            "he was happy when he got a gift",
            "when the sun sets it gets dark",
            "she cries when she is sad",
            "the bird sings when morning comes",
            "they欢呼 when they win",
        ],
        "practice": "Join with when: The bell rings. We line up. -> ___ the bell rings, we line up.",
    },
    {
        "title": "Using If",
        "concept": "If shows a condition. It tells what might happen.",
        "sentences": [
            "if it rains we stay inside",
            "if you study you will learn",
            "she will go if the weather is nice",
            "if you are kind people will like you",
            "if you practice you will improve",
            "it will melt if it gets hot",
            "if you need help ask me",
            "if the tire is flat we can't go",
        ],
        "practice": "Write a sentence with if: ___ if it ___.",
    },
    {
        "title": "Four Sentence Types: Statement",
        "concept": "Declarative sentences make statements and end with a period.",
        "sentences": [
            "the sky is blue",
            "the dog is sleeping",
            "she likes apples",
            "we go to school",
            "the cat caught a mouse",
            "birds can fly",
            "milk comes from cows",
            "winter is cold",
            "the movie was fun",
            "i finished my homework",
        ],
        "practice": "Write 5 statements: ___ . / ___ . / ___ .",
    },
    {
        "title": "Four Sentence Types: Question",
        "concept": "Interrogative sentences ask questions and end with a question mark.",
        "sentences": [
            "what is your name",
            "where are you going",
            "how old are you",
            "why are you crying",
            "when will you arrive",
            "who is your friend",
            "which one do you want",
            "does the dog bark",
            "is it raining outside",
            "can you help me",
        ],
        "practice": "Write 5 questions: ___ ? / ___ ? / ___ ?",
    },
    {
        "title": "Four Sentence Types: Exclamation",
        "concept": "Exclamatory sentences show strong feeling and end with exclamation point.",
        "sentences": [
            "what a beautiful sunset",
            "that was amazing",
            "how fast he runs",
            "what a smart idea",
            "that is wonderful news",
            "how exciting",
            "what a nice surprise",
            "that hurt",
            "wow that is big",
            "oh no",
        ],
        "practice": "Write 5 exclamations: ___ ! / ___ !",
    },
    {
        "title": "Four Sentence Types: Command",
        "concept": "Imperative sentences give commands or make requests. They end with a period or exclamation.",
        "sentences": [
            "please close the door",
            "sit down now",
            "be quiet in the library",
            "don't run in the hallway",
            "finish your homework",
            "wait for me here",
            "pass the salt please",
            "stop that immediately",
            "help your brother",
            "remember to study",
        ],
        "practice": "Write 5 commands: ___ . / ___ !",
    },
    {
        "title": "Compound Sentences with And",
        "concept": "A compound sentence joins two complete ideas with AND.",
        "sentences": [
            "i like math and i like science",
            "she reads books and she writes stories",
            "the dog barked and the cat hissed",
            "we played outside and we got dirty",
            "he studied hard and he passed the test",
            "the sun rose and the birds sang",
            "she cooked dinner and he set the table",
            "they walked to school and they arrived on time",
        ],
        "practice": "Combine with and: I like apples. I like oranges. -> I like apples ___ oranges.",
    },
    {
        "title": "Compound Sentences with But",
        "concept": "But shows contrast between two ideas.",
        "sentences": [
            "i like summer but i don't like winter",
            "she is smart but she is shy",
            "he runs fast but he didn't win",
            "the book is long but it is interesting",
            "it was raining but we went outside",
            "i am tired but i have to finish",
            "the test was hard but most students passed",
            "she was scared but she didn't cry",
        ],
        "practice": "Combine with but: It was cold. We went outside. -> It was cold ___ we went outside.",
    },
    {
        "title": "Compound Sentences with Or",
        "concept": "Or gives a choice between two ideas.",
        "sentences": [
            "you can have ice cream or cake",
            "we can walk to school or take the bus",
            "she can read a book or watch a movie",
            "you can go now or wait until later",
            "he can play soccer or basketball",
            "it is raining or it is just cloudy",
            "the answer is yes or no",
            "come to class on time or you will be late",
        ],
        "practice": "Combine with or: You can study. You can sleep. -> You can study ___ you can sleep.",
    },
    {
        "title": "Apostrophes for Possession",
        "concept": "Add apostrophe S to show something belongs to someone.",
        "sentences": [
            "the boy's ball",
            "the girl's book",
            "mary's cat",
            "the dog's tail",
            "the teacher's desk",
            "mom's car",
            "the children's toys",
            "my friend's house",
            "the farmer's field",
            "the bird's nest",
        ],
        "practice": "Fix: the ball of the boy -> ___ ball / the hat of mom -> ___ hat",
    },
    {
        "title": "Apostrophes in Contractions",
        "concept": "Contractions use apostrophes to replace missing letters.",
        "sentences": [
            "it is -> it's",
            "i am -> i'm",
            "you are -> you're",
            "he is -> he's",
            "she is -> she's",
            "we are -> we're",
            "they are -> they're",
            "i have -> i've",
            "we will -> we'll",
            "they would -> they'd",
        ],
        "practice": "Fix the spaces: it is cold -> ___ / she will go -> ___ / they have seen -> ___",
    },
    {
        "title": "Order Words: First, Next, Then, Last",
        "concept": "These words show the ORDER of events.",
        "sentences": [
            "first we wake up then we eat breakfast next we get dressed last we go to school",
            "first the sun rises next the birds sing then the temperature rises last it is noon",
            "first i open the book next i read the words then i answer the questions last i check my work",
        ],
        "practice": "Put in order: ___ we eat lunch / ___ we go home / ___ we finish class / ___ we go to recess",
    },
    {
        "title": "Adjectives After Be Verbs",
        "concept": "After is, am, are, was, were, adjectives describe the subject.",
        "sentences": [
            "the sky is blue",
            "she is happy",
            "they are tired",
            "it was cold yesterday",
            "we were excited",
            "the movie was interesting",
            "the children are noisy",
            "he is tall for his age",
            "the water feels cold",
            "these apples are red",
        ],
        "practice": "Fill in with an adjective: The sky is ___. / She is ___. / They were ___.",
    },
    {
        "title": "Prepositions: In, On, At, To, From",
        "concept": "Prepositions show location and direction.",
        "sentences": [
            "the cat is in the box",
            "the book is on the table",
            "we are at school",
            "she went to the store",
            "they came from home",
            "put it in the bag",
            "jump on the bed",
            "look at me",
            "go to sleep",
            "walk from the door",
        ],
        "practice": "Fill in with in, on, at, to, or from: Put the ball ___ the box. / Go ___ the door.",
    },
    {
        "title": "Pronouns After Prepositions",
        "concept": "Use object pronouns after prepositions: me, you, him, her, it, us, them.",
        "sentences": [
            "give it to me",
            "she talked to him",
            "the gift is for her",
            "come with us",
            "they played with them",
            "look at me",
            "sit between you and me",
            "the book belongs to him",
            "give the ball to them",
            "she went with us",
        ],
        "practice": "Replace with pronoun: Give the ball to Tom -> Give the ball to ___. / Look at Dad -> Look at ___.",
    },
    {
        "title": "Double Negatives: No Not Nothing",
        "concept": "Don't use two negatives in one sentence. One negative is enough.",
        "sentences": [
            "correct: i don't have any money",
            "incorrect: i don't have no money",
            "correct: she doesn't know anything",
            "incorrect: she doesn't know nothing",
            "correct: there is no milk left",
            "incorrect: there isn't no milk left",
            "correct: i can't see anything",
            "incorrect: i can't see nothing",
        ],
        "practice": "Fix the double negative: I don't have no friends. / She doesn't want nothing. / There isn't no way.",
    },
    {
        "title": "Subject and Verb Agreement: I and You",
        "concept": "With I and you, the verb doesn't add s. With he, she, it, the verb adds s.",
        "sentences": [
            "i walk to school",
            "you walk to school",
            "he walks to school",
            "she walks to school",
            "it walks on four legs",
            "i run fast",
            "you run fast",
            "he runs fast",
            "she runs fast",
            "it runs fast",
        ],
        "practice": "Fix: She walk fast. / He runs fast. / They runs together.",
    },
    {
        "title": "Subject and Verb Agreement: We and They",
        "concept": "With we and they, the verb doesn't add s.",
        "sentences": [
            "we play at recess",
            "they play at recess",
            "we read books",
            "they read books",
            "we help each other",
            "they help each other",
            "we go to school",
            "they go to school",
            "we finish our work",
            "they finish their work",
        ],
        "practice": "Fix: We plays together. / They plays together. / We goes home.",
    },
    {
        "title": "Using Too and Enough",
        "concept": "Too means more than needed. Enough means just right or sufficient.",
        "sentences": [
            "the book is too hard for me",
            "she is tall enough to reach",
            "it is too hot today",
            "he is strong enough to lift",
            "the bag is too heavy",
            "we have enough time",
            "the water is too cold to swim",
            "i am tall enough for the ride",
            "this is too much work",
            "there is enough food",
        ],
        "practice": "Choose too or enough: The bag is ___ heavy to carry. / I am tall ___ for the ride.",
    },
    {
        "title": "Homophones: There, Their, They're",
        "concept": "There (place), their (belonging), they're (they are) sound the same but mean different things.",
        "sentences": [
            "the books are over there",
            "their books are on the table",
            "they're going to the library",
            "put it there by them",
            "their house is big",
            "they're coming home now",
            "the dog is there",
            "their dog is friendly",
            "they're being silly",
            "please sit over there",
        ],
        "practice": "Choose there, their, or they're: ___ books are new. / ___ going home. / Sit ___.",
    },
    {
        "title": "Homophones: To, Too, Two",
        "concept": "To (direction), too (also or excessive), two (the number 2) sound similar but mean different things.",
        "sentences": [
            "i went to the store",
            "i want to come too",
            "this is too hot",
            "two plus two equals four",
            "give the book to her",
            "she is hungry too",
            "the problem is too hard",
            "two and two make four",
            "go to bed now",
            "i want some too",
        ],
        "practice": "Choose to, too, or two: I want ___ come. / This is ___ hot. / ___ plus ___ equals four.",
    },
    {
        "title": "Homophones: Your and You're",
        "concept": "Your shows ownership. You're means you are.",
        "sentences": [
            "your book is on the table",
            "you're going to love this",
            "is that your bag",
            "you're a good student",
            "your mom is here",
            "you're coming to the party",
            "put your things away",
            "you're almost done",
        ],
        "practice": "Choose your or you're: ___ coming to my house. / Is that ___ book? / ___ mom is nice.",
    },
    {
        "title": "Homophones: Its and It's",
        "concept": "It's means it is or it has. Its shows possession.",
        "sentences": [
            "it's a beautiful day",
            "the dog wagged its tail",
            "it's been raining all day",
            "the cat licked its paw",
            "it's too hot outside",
            "the tree lost its leaves",
            "it's my turn now",
            "the bird built its nest",
        ],
        "practice": "Choose its or it's: ___ a sunny day. / The dog wagged ___ tail. / ___ been snowing.",
    },
    {
        "title": "Review: Fix the Sentences",
        "concept": "Find and fix errors in capitalization, punctuation, and grammar.",
        "sentences": [
            "the boy runs fast",
            "is the sky blue",
            "what a big dog",
            "she go to school",
            "the book are on the table",
            "i dont have no money",
            "him and me are friends",
            "the dog wags it tail",
        ],
        "practice": "Fix each sentence: the cat are here / she don't have no help / him and me is going",
    },
    {
        "title": "Complete Grammar Review",
        "concept": "Review all 2nd grade grammar concepts.",
        "sentences": [
            "the children went to the park yesterday",
            "they played on the swings and slid down the slide",
            "sarah and jake were there too",
            "the sun was shining bright",
            "it wasn't too hot outside",
            "they're having a great time",
            "the dog's ball rolled into the pond",
            "jake got his ball back because it floated",
            "they're going back tomorrow",
        ],
        "practice": "Identify: 2 proper nouns / 1 contraction / 1 past tense verb / 1 plural noun",
    },
]


def get_grammar_lessons(grade, full=True):
    if grade == 2:
        return LESSONS_FULL_40 if full else LESSONS_BASELINE_10
    return []


def get_all_grammar_sentences(grade=2, full=True):
    lessons = get_grammar_lessons(grade, full)
    sentences = []
    for lesson in lessons:
        sentences.extend(lesson["sentences"])
    return sentences


def get_lesson_by_title(title, grade=2, full=True):
    lessons = get_grammar_lessons(grade, full)
    for lesson in lessons:
        if lesson["title"].lower() == title.lower():
            return lesson
    return None