"""
3rd Grade Grammar Lessons - 40 lessons covering:
- Subject-verb agreement
- Progressive tenses
- Complex sentences (because, when, although)
- Adverbs (modify verbs, adjectives)
- Apostrophes (possession)
- Conjunctions
- Four sentence types
- Quotation marks
"""

LESSONS_BASELINE_15 = [
    {
        "title": "Subject-Verb Agreement: Present",
        "concept": "The verb must match the subject. He walks. They walk. I walk.",
        "sentences": [
            "he walks to school every day",
            "she walks to school every day",
            "they walk to school every day",
            "we walk to school every day",
            "the dog walks on a leash",
            "the dogs walk in the park",
            "she reads books every week",
            "they read books every week",
            "it barks loudly",
            "they bark loudly",
        ],
        "practice": "Choose the correct verb: He ___ (walk/walks) fast. / They ___ (run/runs) fast.",
    },
    {
        "title": "Subject-Verb Agreement: Past",
        "concept": "Past tense verbs also must match subjects.",
        "sentences": [
            "he walked to school yesterday",
            "she walked to school yesterday",
            "they walked to school yesterday",
            "we walked to school yesterday",
            "the dog walked on a leash",
            "the dogs walked in the park",
            "she read books last week",
            "they read books last week",
            "it barked loudly",
            "they barked loudly",
        ],
        "practice": "Choose the correct verb: He ___ (walk/walked) fast. / They ___ (run/ran) fast.",
    },
    {
        "title": "Subject-Verb Agreement: With Contractions",
        "concept": "Contractions still need matching subjects and verbs.",
        "sentences": [
            "he's walking to school",
            "she's walking to school",
            "they're walking to school",
            "we're walking to school",
            "it's running fast",
            "they're running fast",
            "she's reading a book",
            "he's reading a book",
            "it's barking loud",
            "they're barking loud",
        ],
        "practice": "Fix: He's walk to school. / She's reads a book. / They're runs fast.",
    },
    {
        "title": "Progressive Tense: Was and Were",
        "concept": "Use was with I, he, she, it. Use were with you, we, they.",
        "sentences": [
            "i was walking to school",
            "he was walking to school",
            "she was walking to school",
            "it was walking fast",
            "you were walking to school",
            "we were walking to school",
            "they were walking to school",
            "i was reading a book",
            "she was reading a book",
            "they were reading books",
        ],
        "practice": "Choose was or were: I ___ walking. / They ___ walking. / She ___ reading.",
    },
    {
        "title": "Progressive Tense: Is and Are with Ing",
        "concept": "Present progressive uses is/are + verb with ING.",
        "sentences": [
            "he is walking to school",
            "she is walking to school",
            "it is running fast",
            "they are walking to school",
            "we are walking to school",
            "i am walking to school",
            "you are walking to school",
            "the dog is barking loud",
            "the birds are singing beautiful",
            "the children are playing outside",
        ],
        "practice": "Add is/are and ING: He ___ (walk) to school. / They ___ (play) in the park.",
    },
    {
        "title": "Progressive Tense: Will Be",
        "concept": "Future progressive uses will be + verb with ING.",
        "sentences": [
            "he will be walking to school",
            "she will be walking to school",
            "they will be walking to school",
            "we will be walking to school",
            "it will be running fast",
            "you will be walking to school",
            "i will be walking to school",
            "the dog will be barking",
            "the birds will be singing",
            "the children will be playing",
        ],
        "practice": "Add will be and ING: He ___ (walk) to school. / They ___ (play) in the park.",
    },
    {
        "title": "Complex Sentences: Because",
        "concept": "Because shows WHY. The clause after because gives the reason.",
        "sentences": [
            "she studied because she wanted to pass",
            "the dog barked because it was hungry",
            "he was tired because he stayed up late",
            "plants need water because they are living things",
            "the cat hid because it was scared",
            "she smiled because she was happy",
            "the road was wet because it rained",
            "he ate because he was hungry",
            "they celebrated because they won",
            "the class was quiet because the teacher was strict",
        ],
        "practice": "Join: She was sad. She failed the test. -> She was sad ___ ___ ___.",
    },
    {
        "title": "Complex Sentences: When",
        "concept": "When shows WHEN something happens.",
        "sentences": [
            "when the bell rings we line up",
            "she reads when she is tired",
            "the flowers bloom when spring comes",
            "he was happy when he got a gift",
            "when the sun sets it gets dark",
            "she cries when she is sad",
            "the bird sings when morning comes",
            "they欢呼 when they win",
            "when you need help ask me",
            "when the tire is flat we can't go",
        ],
        "practice": "Join: The bell rings. We line up. -> ___ the bell rings, we ___.",
    },
    {
        "title": "Complex Sentences: Although",
        "concept": "Although shows contrast. It means BUT.",
        "sentences": [
            "although it was raining we went outside",
            "she passed although she didn't study",
            "he is tall although his parents are short",
            "the book is long although it is interesting",
            "although it was cold they went swimming",
            "she is smart although she makes mistakes",
            "although he was tired he finished the work",
            "the food is hot although it is just cooked",
            "although it was expensive she bought it",
            "he ran fast although he was injured",
        ],
        "practice": "Join with although: It was raining. We went outside. -> ___ it was raining, we ___ outside.",
    },
    {
        "title": "Adverbs: Modify Verbs",
        "concept": "Adverbs tell HOW something happens. They often end in LY.",
        "sentences": [
            "she sings beautifully",
            "he runs quickly",
            "they speak softly",
            "the turtle moves slowly",
            "please listen carefully",
            "the baby sleeps peacefully",
            "the artist draws neatly",
            "students work quietly",
            "the fire burns brightly",
            "the rain falls softly",
        ],
        "practice": "Add an adverb: She sings ___. / He runs ___. / They speak ___.",
    },
    {
        "title": "Adverbs: Modify Adjectives",
        "concept": "Adverbs can also modify adjectives to make them stronger or weaker.",
        "sentences": [
            "the sky is very blue",
            "she is quite tall",
            "it is extremely hot today",
            "he is really happy",
            "the book is rather interesting",
            "the food is very delicious",
            "she seems quite tired",
            "it was extremely cold",
            "he is very tall for his age",
            "the movie was really exciting",
        ],
        "practice": "Add very, quite, really, or extremely: The sky is ___ blue. / She is ___ tired.",
    },
    {
        "title": "Apostrophes for Possession: Singular",
        "concept": "Add apostrophe S to singular nouns to show possession.",
        "sentences": [
            "the boy's ball",
            "the girl's book",
            "mary's cat",
            "the teacher's desk",
            "my mom's car",
            "the dog's tail",
            "tom's house",
            "the child's toy",
            "the woman's bag",
            "the man's hat",
        ],
        "practice": "Fix: the ball of the boy -> ___ / the book of mary -> ___ / the car of my mom -> ___",
    },
    {
        "title": "Apostrophes for Possession: Plural",
        "concept": "For plural nouns ending in S, add apostrophe after the S.",
        "sentences": [
            "the boys' ball",
            "the girls' books",
            "the teachers' room",
            "the dogs' owners",
            "the cats' toys",
            "the children's playground",
            "my parents' house",
            "the students' desks",
            "the birds' nest",
            "the workers' tools",
        ],
        "practice": "Fix: the ball of the boys -> ___ / the books of the girls -> ___ / the room of the teachers -> ___",
    },
    {
        "title": "Conjunctions: And, But, Or, Because, Although",
        "concept": "Conjunctions join words or groups of words.",
        "sentences": [
            "i like apples and bananas",
            "i like summer but not winter",
            "you can run or walk",
            "she studied because she wanted to pass",
            "although it rained we went outside",
            "he is smart but lazy",
            "we can go now or later",
            "she reads and writes well",
            "they came because you invited them",
            "although it was expensive it was worth it",
        ],
        "practice": "Fill in with and, but, or, because, although: I like red ___ blue. / She went ___ she was sick.",
    },
    {
        "title": "Four Sentence Types: Practice",
        "concept": "Statements end with period. Questions end with ?. Exclamations end with ! Commands give orders.",
        "sentences": [
            "the sun rises in the east",
            "does the sun rise in the west",
            "what a beautiful sunrise",
            "watch the sunrise tomorrow",
            "the dog is sleeping",
            "is the dog sleeping",
            "what a sleepy dog",
            "let the dog sleep",
            "the cat is on the roof",
            "is the cat on the roof",
        ],
        "practice": "Write each type about: The baby / The baby ___ ? / ___ baby ! / The baby ___ .",
    },
]


LESSONS_FULL_40 = LESSONS_BASELINE_15 + [
    {
        "title": "Quotation Marks: Direct Speech",
        "concept": "Use quotation marks to show exactly what someone said.",
        "sentences": [
            "she said hello",
            "the teacher said quiet",
            "he shouted stop",
            "mom said time for bed",
            "dad said good job",
            "she whispered secret",
            "the coach said go team",
            "he asked question",
        ],
        "practice": "Add quotation marks: She said go to school. / He shouted help.",
    },
    {
        "title": "Commas in a Series",
        "concept": "Use commas to separate three or more items in a series.",
        "sentences": [
            "apples bananas and oranges",
            "she reads writes and draws",
            "monday tuesday and wednesday",
            "red blue and green",
            "i like to run jump and play",
            "the dog barked growled and bit",
            "he ate meat vegetables and fruit",
            "we went to the park library and store",
        ],
        "practice": "Add commas: Apples oranges and bananas. / She reads writes and draws.",
    },
    {
        "title": "Commas with Direct Speech",
        "concept": "Use commas after words that introduce what someone said.",
        "sentences": [
            "she said i am happy",
            "mom said it is time to go",
            "the teacher said open your books",
            "he said i will try",
            "dad said good morning",
            "she replied i understand",
            "the boy said please help me",
            "the girl said thank you",
        ],
        "practice": "Add commas: She said i am happy. / Mom said it is time to eat.",
    },
    {
        "title": "Capitalization: Titles",
        "concept": "Capitalize titles before names but not after.",
        "sentences": [
            "doctor jones is here",
            "mrs smith teaches us",
            "president lincoln was tall",
            "professor hansen is kind",
            "captain america is a hero",
            "queen elizabeth is famous",
            "doctor who is a show",
            "uncle sam needs you",
        ],
        "practice": "Fix: doctor smith is here. / president washington was first.",
    },
    {
        "title": "Helping Verbs: Can, Could, Will, Would",
        "concept": "Helping verbs work with main verbs to show ability, possibility, or future.",
        "sentences": [
            "i can swim in the pool",
            "she could read at age four",
            "we will go to school tomorrow",
            "i would like some water",
            "he can run very fast",
            "they could win the game",
            "it will rain later",
            "she would help if asked",
            "you can do it",
            "we could try again",
        ],
        "practice": "Fill in the helping verb: I ___ swim. / She ___ read. / They ___ go.",
    },
    {
        "title": "Helping Verbs: Has, Have, Had",
        "concept": "Has, have, had show possession or completion.",
        "sentences": [
            "she has a beautiful smile",
            "they have a big house",
            "he had a bad dream",
            "i have finished my work",
            "the dog has a new collar",
            "we have seen that movie",
            "she had already left",
            "they have been waiting long",
        ],
        "practice": "Choose has, have, or had: She ___ a car. / They ___ a house. / He ___ a dog.",
    },
    {
        "title": "Helping Verbs: Is, Are, Was, Were + Ing",
        "concept": "These helping verbs work with ing to show ongoing action.",
        "sentences": [
            "she is reading a book",
            "they are playing outside",
            "he was running fast",
            "we were watching a movie",
            "it is raining today",
            "the birds are singing beautiful",
            "i was thinking about you",
            "they were talking loud",
        ],
        "practice": "Fill in is/are/was/were + ing: She ___ (read) a book. / They ___ (play) outside.",
    },
    {
        "title": "Double Negatives: Avoid Them",
        "concept": "Don't use two negatives in one sentence.",
        "sentences": [
            "correct: i don't have any money",
            "incorrect: i don't have no money",
            "correct: she doesn't know anything",
            "incorrect: she doesn't know nothing",
            "correct: there is no milk left",
            "incorrect: there isn't no milk left",
            "correct: i can't see anything",
            "incorrect: i can't see nothing",
            "correct: we haven't seen anyone",
            "incorrect: we haven't seen nobody",
        ],
        "practice": "Fix: I don't have no friends. / She doesn't want nothing. / There isn't no way.",
    },
    {
        "title": "Run-On Sentences",
        "concept": "Don't run two complete sentences together without proper punctuation.",
        "sentences": [
            "i like math it is fun",
            "she runs fast she wins",
            "the dog barked it was loud",
            "we went to the park we played",
            "he studied he passed the test",
            "she is smart she is kind",
            "it rained all day the streets flooded",
            "they walked to school they arrived on time",
        ],
        "practice": "Fix by adding period or comma: I like math it is fun. -> I like math. ___",
    },
    {
        "title": "Sentence Fragments",
        "concept": "Fragments are incomplete sentences missing subject, verb, or complete thought.",
        "sentences": [
            "the boy who lost his dog",
            "ran through the park",
            "because she was tired",
            "a beautiful sunset over",
            "jumped up and down",
            "the girl in the red dress",
            "went to the store",
            "quickly and quietly",
            "because the weather was cold",
            "the cat on the roof",
        ],
        "practice": "Fix each fragment: Ran through the park. / Because she was tired.",
    },
    {
        "title": "Sentence Combining: With Conjunctions",
        "concept": "Join short sentences with conjunctions for smoother writing.",
        "sentences": [
            "the boy is tall he plays basketball",
            "she studied hard she got an a",
            "the dog barked it chased the cat",
            "it was raining we stayed inside",
            "he is smart he is lazy",
            "the food is good it is healthy",
            "she reads books she writes stories",
            "we played outside we got dirty",
        ],
        "practice": "Combine: The sky is blue. The clouds are white. -> The sky is blue ___ the clouds are white.",
    },
    {
        "title": "Sentences with Participial Phrases",
        "concept": "Add ing phrases to describe what someone is doing.",
        "sentences": [
            "the boy running down the street is my brother",
            "she found the book lying on the floor",
            "the dog barking at the mailman is scary",
            "they watched the sunset setting behind the hill",
            "the children playing in the park are happy",
            "he saw the cat sleeping on the couch",
            "the teacher grading papers is mrs johnson",
            "the bird flying south is a goose",
        ],
        "practice": "Add an ing phrase: The boy ___ is my brother. / She found the book ___.",
    },
    {
        "title": "Using Since and Until",
        "concept": "Since shows starting time. Until shows ending time.",
        "sentences": [
            "i have lived here since twenty twenty",
            "wait until three o'clock",
            "she has been sick since monday",
            "don't leave until i come back",
            "since you asked i will tell you",
            "read until you finish the book",
            "he has been working since early morning",
            "stay here until the storm passes",
        ],
        "practice": "Fill in since or until: Wait ___ tomorrow. / I have been here ___ last week.",
    },
    {
        "title": "Using Unless",
        "concept": "Unless means IF NOT. It shows a condition.",
        "sentences": [
            "unless you study you won't pass",
            "i won't go unless you come with me",
            "the plant will die unless you water it",
            "unless it stops raining we can't play outside",
            "she can't come unless she gets permission",
            "unless you ask no one will help you",
            "the cake won't rise unless you add yeast",
            "unless you practice you won't improve",
        ],
        "practice": "Write sentences with unless: ___ unless ___.",
    },
    {
        "title": "Using Whether",
        "concept": "Whether shows a choice between two things.",
        "sentences": [
            "i don't know whether to go or stay",
            "tell me whether you like it or not",
            "she wondered whether to call him",
            "whether you win or lose doesn't matter",
            "i'm not sure whether to take the job",
            "whether it rains or shines we go",
            "they asked whether we were coming",
            "it doesn't matter whether you agree",
        ],
        "practice": "Write sentences with whether: ___ whether ___ or ___.",
    },
    {
        "title": "Adjective Clauses: Who and Which",
        "concept": "Use who for people and which for things to add more information.",
        "sentences": [
            "the girl who won the race is my sister",
            "the book which is on the table is mine",
            "the boy who sits next to me is nice",
            "the car which is red belongs to my dad",
            "the teacher who teaches math is strict",
            "the house which has a blue door is old",
            "the student who finished early helped others",
            "the dog which barked all night is gone",
        ],
        "practice": "Add who or which: The boy ___ sits here is kind. / The book ___ is new is interesting.",
    },
    {
        "title": "Pronoun Case: Subject vs Object",
        "concept": "Use subject pronouns (I, you, he, she, it, we, they) as subjects. Use object pronouns (me, you, him, her, it, us, them) after verbs or prepositions.",
        "sentences": [
            "she and i went to the store",
            "the teacher gave them their homework",
            "he and she are best friends",
            "the ball hit him on the head",
            "we saw them at the park",
            "she told him the truth",
            "they invited us to the party",
            "the dog followed me home",
        ],
        "practice": "Choose he/she/they or him/her/them: ___ and I went home. / She gave the book to ___.",
    },
    {
        "title": "Using Could Have, Should Have, Would Have",
        "concept": "These show past possibility, obligation, or wish.",
        "sentences": [
            "i could have gone to the party but i was tired",
            "you should have studied more",
            "he would have helped if he knew",
            "she could have missed the bus",
            "we should have left earlier",
            "they would have come if invited",
            "i should have tried harder",
            "you could have done better",
        ],
        "practice": "Complete: I ___ (could have) gone but ___ (should have) stayed home.",
    },
    {
        "title": "Using Should and Shouldn't",
        "concept": "Should shows advice. Shouldn't shows what is not recommended.",
        "sentences": [
            "you should study for the test",
            "you shouldn't waste time",
            "she should eat more vegetables",
            "he shouldn't eat so much candy",
            "we should help others",
            "they shouldn't be rude",
            "you should be kind",
            "shouldn't you apologize",
        ],
        "practice": "Write should or shouldn't: You ___ exercise every day. / You ___ smoke.",
    },
    {
        "title": "Grammar Review: Mixed Practice",
        "concept": "Review all 3rd grade grammar skills.",
        "sentences": [
            "she walked to school because it was a nice day",
            "when the bell rang the children ran outside",
            "the teacher's desk is in the corner of the room",
            "they were playing in the park although it was cold",
            "we've been waiting since eight o'clock",
            "the boy who lost his手套 is crying",
            "you shouldn't have said that",
            "either you come with us or you stay here",
        ],
        "practice": "Identify: 1 complex sentence / 1 contraction / 1 apostrophe possession / 1 adverb",
    },
    {
        "title": "Grammar Review: Error Finding",
        "concept": "Find and fix the errors in each sentence.",
        "sentences": [
            "their going to the park tomorrow",
            "her and me is going",
            "the boys' ball are red",
            "she don't have no money",
            "i havent saw him yet",
            "he runned fast yesterday",
            "the girl which reads is smart",
            "their house is to big",
        ],
        "practice": "Fix each error: Their going home. / Her and me is going.",
    },
]


def get_grammar_lessons(grade, full=True):
    if grade == 3:
        return LESSONS_FULL_40 if full else LESSONS_BASELINE_15
    return []


def get_all_grammar_sentences(grade=3, full=True):
    lessons = get_grammar_lessons(grade, full)
    sentences = []
    for lesson in lessons:
        sentences.extend(lesson["sentences"])
    return sentences


def get_lesson_by_title(title, grade=3, full=True):
    lessons = get_grammar_lessons(grade, full)
    for lesson in lessons:
        if lesson["title"].lower() == title.lower():
            return lesson
    return None