"""
1st Grade Grammar Lessons - 40 lessons covering:
- Sentences: subject + predicate
- Nouns: person, place, thing, animal
- Verbs: action words
- Adjectives: color, size, shape
- Capitalization, punctuation
- Pronouns
- Simple plurals
"""

LESSONS_BASELINE_10 = [
    {
        "title": "What is a Sentence?",
        "concept": "A sentence is a complete thought with a subject and predicate.",
        "sentences": [
            "the dog barks",
            "the cat sleeps",
            "i see a bird",
            "she runs fast",
            "the sun shines",
            "we play games",
            "he jumps high",
            "the rain falls",
            "they smile big",
            "a boy laughs",
        ],
        "practice": "Add subject or predicate: ___ runs fast. / The dog ___.",
    },
    {
        "title": "Subjects and Predicates",
        "concept": "The subject is WHO or WHAT the sentence is about. The predicate tells what the subject does.",
        "sentences": [
            "bird flies",
            "fish swim",
            "frog jumps",
            "bear walks",
            "bee flies",
            "snake slides",
            "cow grazes",
            "pig oinks",
            "duck swims",
            "goat chews",
        ],
        "practice": "Circle the subject, underline the predicate: The cat chased the mouse.",
    },
    {
        "title": "Nouns: People",
        "concept": "Nouns are words for people. A noun names a person.",
        "sentences": [
            "mom cooks dinner",
            "dad fixes the car",
            "teacher helps students",
            "doctor checks patients",
            "baby cries loud",
            "boy throws ball",
            "girl reads book",
            "friends play together",
            "neighbor waves hello",
            "brother shares toys",
        ],
        "practice": "List 5 people nouns: ___ ___ ___ ___ ___",
    },
    {
        "title": "Nouns: Places",
        "concept": "Nouns can name places where things are or happen.",
        "sentences": [
            "we go to school",
            "birds fly in sky",
            "fish swim in ocean",
            "bear lives in forest",
            "cows eat grass in field",
            "children play at park",
            "mom works at office",
            "we shop at store",
            "train travels on tracks",
            "boat floats on lake",
        ],
        "practice": "Name 5 places: ___ ___ ___ ___ ___",
    },
    {
        "title": "Nouns: Things",
        "concept": "Nouns name objects you can see and touch.",
        "sentences": [
            "the ball bounces high",
            "book sits on desk",
            "cup holds water",
            "chair has four legs",
            "clock ticks loud",
            "pen writes smooth",
            "paper folds easy",
            "door opens wide",
            "window lets light in",
            "table holds plates",
        ],
        "practice": "Write 5 thing nouns: ___ ___ ___ ___ ___",
    },
    {
        "title": "Nouns: Animals",
        "concept": "Animals are nouns too! Dogs, cats, birds, and fish are all animals.",
        "sentences": [
            "dog wags tail",
            "cat purrs soft",
            "bird builds nest",
            "fish swims fast",
            "horse gallops quick",
            "sheep gives wool",
            "pig rolls in mud",
            "lion roars loud",
            "monkey swings branch",
            "elephant sprays water",
        ],
        "practice": "Name an animal for each: ___ flies, ___ swims, ___ runs",
    },
    {
        "title": "Verbs: Action Words",
        "concept": "Verbs are action words. They tell what someone or something does.",
        "sentences": [
            "he runs to school",
            "she reads a book",
            "they play at recess",
            "we eat lunch",
            "bird sings beautiful",
            "water flows down",
            "sun rises early",
            "baby sleeps sound",
            "dog fetches ball",
            "cat chases mouse",
        ],
        "practice": "Circle the verb: The boy kicks the ball. / She draws a picture.",
    },
    {
        "title": "Adjectives: Describing Words",
        "concept": "Adjectives describe nouns. They tell what kind, what color, or how many.",
        "sentences": [
            "big bear eats honey",
            "red apple tastes sweet",
            "small mouse hides quick",
            "tall giraffe eats leaves",
            "soft blanket feels warm",
            "round ball bounces high",
            "green frog sits still",
            "brown dog runs fast",
            "blue sky looks pretty",
            "hot fire burns bright",
        ],
        "practice": "Add an adjective: ___ dog, ___ sun, ___ tree",
    },
    {
        "title": "Capitalization: Beginning of Sentences",
        "concept": "Every sentence begins with a capital letter.",
        "sentences": [
            "the dog barks loud",
            "children play outside",
            "sun shines bright",
            "rain falls down",
            "bird sings sweet",
            "mom cooks dinner",
            "book has pages",
            "car drives fast",
            "fish swim deep",
            "bear catches fish",
        ],
        "practice": "Fix the capitalization: the boy runs. the girl jumps.",
    },
    {
        "title": "Punctuation: Period, Question Mark, Exclamation",
        "concept": "Sentences end with punctuation. Statements end with period. Questions end with ?. Excitement ends with !",
        "sentences": [
            "the cat is big",
            "is the cat big",
            "what a big cat",
            "the dog runs fast",
            "does the dog run fast",
            "what a fast dog",
            "she reads books",
            "does she read books",
            "what a smart reader",
        ],
        "practice": "Add correct ending: What time is it / I like ice cream / Wow that is big",
    },
    {
        "title": "Pronouns: I, You, He, She, It, We, They",
        "concept": "Pronouns take the place of nouns. I replaces your name when you talk about yourself.",
        "sentences": [
            "i see the bird",
            "you can help me",
            "he runs fast",
            "she reads books",
            "it is sunny today",
            "we play together",
            "they wave hello",
            "i am happy",
            "she is kind",
            "it is blue",
        ],
        "practice": "Replace with pronoun: ___ saw the dog. The dog ran away. -> ___ ran away.",
    },
    {
        "title": "Simple Plurals",
        "concept": "When there is more than one, add s to most nouns.",
        "sentences": [
            "one cat, two cats",
            "one dog, two dogs",
            "one bird, many birds",
            "one fish, several fish",
            "one book, many books",
            "one ball, three balls",
            "one tree, five trees",
            "one star, many stars",
            "one girl, four girls",
            "one boy, many boys",
        ],
        "practice": "Make plural: one cat, two ___ / one dog, three ___ / one bird, many ___",
    },
    {
        "title": "Combining Sentences with And",
        "concept": "You can join two ideas with the word AND.",
        "sentences": [
            "the boy runs and jumps",
            "the girl reads and draws",
            "the dog barks and wags tail",
            "sun shines and birds sing",
            "mom cooks and dad sets table",
            "he writes and she reads",
            "cats purr and dogs bark",
            "fish swim and birds fly",
            "i eat and drink",
            "we play and learn",
        ],
        "practice": "Combine: The cat purrs. The cat sleeps. -> The cat purrs ___ sleeps.",
    },
    {
        "title": "Is, Are, Was, Were",
        "concept": "Use IS/WAS for one thing. Use ARE/WERE for more than one.",
        "sentences": [
            "she is happy",
            "they are friends",
            "it was cold yesterday",
            "we were at school",
            "he is tall",
            "they were at the park",
            "the cat is asleep",
            "the cats are playing",
            "i was in class",
            "you were late",
        ],
        "practice": "Choose is or are: There ___ many dogs. / There ___ one cat.",
    },
    {
        "title": "Review: Complete Sentences",
        "concept": "A complete sentence has a subject and predicate and makes sense.",
        "sentences": [
            "the horse runs fast",
            "children eat lunch",
            "sun sets in west",
            "moon shines at night",
            "bear catches fish",
            "birds fly south",
            "frog sits on lily pad",
            "rainbow appears after rain",
            "butterfly lands on flower",
            "squirrel gathers nuts",
        ],
        "practice": "Write a complete sentence about each: A dog ___. The bird ___. ___ runs fast.",
    },
]


LESSONS_FULL_40 = LESSONS_BASELINE_10 + [
    {
        "title": "This, That, These, Those",
        "concept": "This and that refer to one item. These and those refer to more than one.",
        "sentences": [
            "this book is mine",
            "that book is hers",
            "these books are ours",
            "those books are theirs",
            "this apple is red",
            "that apple is green",
            "these apples are sweet",
            "those apples are sour",
        ],
        "practice": "Choose this or these: ___ dog is big. / ___ dogs are big.",
    },
    {
        "title": "In, On, Under, Behind, In Front Of",
        "concept": "Prepositions tell where something is located.",
        "sentences": [
            "the cat is in the box",
            "the book is on the table",
            "the ball is under the chair",
            "the tree is behind the house",
            "the flower is in front of the door",
            "the dog is on the bed",
            "the cat is under the table",
            "the bird is behind the tree",
        ],
        "practice": "Fill in: The book is ___ the desk. / The ball is ___ the table.",
    },
    {
        "title": "Can, Could, Will, Would",
        "concept": "Modal verbs show ability and possibility.",
        "sentences": [
            "i can jump high",
            "she could read at age four",
            "we will go to school",
            "i would like water",
            "he can swim fast",
            "they could win the game",
            "it will rain tomorrow",
            "she would help if asked",
        ],
        "practice": "Choose can or will: It ___ rain today. / She ___ run very fast.",
    },
    {
        "title": "Has, Have, Had",
        "concept": "Use HAS when one thing has something. Use HAVE when more than one has something.",
        "sentences": [
            "she has a cat",
            "they have a dog",
            "he has brown eyes",
            "we have a ball",
            "it has four legs",
            "i have a book",
            "the house has a roof",
            "the car has wheels",
        ],
        "practice": "Choose has or have: She ___ a pet. / They ___ a house.",
    },
    {
        "title": "Doing Words Ending in Ing",
        "concept": "Add ING to many verbs to show an action happening right now.",
        "sentences": [
            "the baby is crying",
            "the children are playing",
            "i am reading a book",
            "she is cooking dinner",
            "they are running fast",
            "we are learning english",
            "he is jumping high",
            "the dog is barking loud",
        ],
        "practice": "Add ING: She is ___(run). / They are ___(swim).",
    },
    {
        "title": "Opposite Words: Big and Small",
        "concept": "Opposites are words that mean the opposite of each other.",
        "sentences": [
            "the elephant is big but the mouse is small",
            "the sun is hot but ice is cold",
            "the path is long but the line is short",
            "the rock is hard but the pillow is soft",
            "the day is bright but the night is dark",
            "the adult is tall but the child is short",
            "the ocean is deep but the puddle is shallow",
            "the mountain is high but the valley is low",
        ],
        "practice": "Write the opposite: tall / ___ , hot / ___ , day / ___",
    },
    {
        "title": "Same Meaning: Happy and Glad",
        "concept": "Some words have similar meanings. Happy and glad both mean feeling joy.",
        "sentences": [
            "i am happy to see you / i am glad to see you",
            "she was pleased with the gift / she was happy with the gift",
            "they were delighted to come / they were glad to come",
            "the news made us joyful / the news made us happy",
        ],
        "practice": "Write a sentence using both: happy and sad / fast and quick / big and large",
    },
    {
        "title": "Adding S to Verbs",
        "concept": "When the subject is he, she, or it, add s or es to the verb.",
        "sentences": [
            "he runs fast",
            "she plays soccer",
            "it barks loud",
            "he catches the ball",
            "she watches tv",
            "it buzzes noisy",
            "he fixes the car",
            "she kisses the baby",
        ],
        "practice": "Add s or es: He ___ (run) fast. / She ___ (play) piano.",
    },
    {
        "title": "Words That Tell When: Yesterday, Today, Tomorrow",
        "concept": "Time words tell us WHEN something happens.",
        "sentences": [
            "yesterday i went to school",
            "today i am at home",
            "tomorrow i will play outside",
            "yesterday was cold",
            "today is warm",
            "tomorrow will be hot",
            "she played yesterday",
            "she plays today",
            "she will play tomorrow",
        ],
        "practice": "Fill in with yesterday, today, or tomorrow: ___ is my birthday. / ___ was Easter.",
    },
    {
        "title": "Words That Tell Where: Here and There",
        "concept": "Here means this place. There means that place.",
        "sentences": [
            "come here to me",
            "go there to the door",
            "the book is here",
            "the book is there",
            "put it here on the table",
            "put it there on the shelf",
            "i am here now",
            "they were there yesterday",
        ],
        "practice": "Choose here or there: Put the ball ___. / Come ___ please.",
    },
    {
        "title": "Names and Places Need Capital Letters",
        "concept": "Names of people and places always start with capital letters.",
        "sentences": [
            "my name is tom",
            "i live in boston",
            "she goes to lincoln school",
            "we visited new york city",
            "mary and john are friends",
            "the amazon river is long",
            "china is a country",
            "mount everest is tall",
        ],
        "practice": "Fix the capitals: i go to school. / her name is sarah. / they live in denver.",
    },
    {
        "title": "More Than One: Adding Es",
        "concept": "Words ending in ch, sh, s, x, z need es to make plural.",
        "sentences": [
            "one box, two boxes",
            "one bus, three buses",
            "one dish, many dishes",
            "one kiss, sweet kisses",
            "one fox, two foxes",
            "one church, many churches",
            "one bus, the buses",
            "one dress, pretty dresses",
        ],
        "practice": "Add es: one box -> two ___ / one bus -> three ___",
    },
    {
        "title": "Words That Tell How: Carefully, Quickly, Slowly",
        "concept": "Adverbs can tell HOW something is done.",
        "sentences": [
            "she writes carefully",
            "he runs quickly",
            "the turtle walks slowly",
            "the bee flies嗡嗡",
            "please speak softly",
            "work quietly",
            "climb carefully",
            "read slowly",
        ],
        "practice": "Add an adverb: She runs ___. / He writes ___.",
    },
    {
        "title": "A and An",
        "concept": "Use A before consonant sounds. Use AN before vowel sounds.",
        "sentences": [
            "a ball",
            "an apple",
            "a cat",
            "an elephant",
            "a dog",
            "an igloo",
            "a zebra",
            "an orange",
        ],
        "practice": "Choose a or an: ___ dog / ___ cat / ___ egg / ___ house",
    },
    {
        "title": "I Love, I Am, I Have",
        "concept": "I is always followed by love, am, or have (not loves, is, haves).",
        "sentences": [
            "i love my family",
            "i am happy today",
            "i have a pet",
            "i love to read",
            "i am a student",
            "i have two books",
            "i am in first grade",
            "i have a ball",
        ],
        "practice": "Fix the error: I loves my dog. / I is happy. / I haves a cat.",
    },
    {
        "title": "Use and, But, Or to Join Ideas",
        "concept": "And joins similar ideas. But shows contrast. Or gives a choice.",
        "sentences": [
            "i like apples and bananas",
            "i like cake but not pie",
            "you can run or walk",
            "she reads and writes",
            "he is tall but small",
            "we can go now or later",
            "the dog barks and wags tail",
            "it is hot but not humid",
        ],
        "practice": "Fill in and, but, or: I like red ___ blue. / She runs fast ___ jumps high.",
    },
    {
        "title": "Using My, Your, His, Her, Our, Their",
        "concept": "These words show ownership or possession.",
        "sentences": [
            "this is my book",
            "is that your bag",
            "he lost his hat",
            "she found her pencil",
            "we did our homework",
            "they finished their work",
            "my mom is nice",
            "your dad is tall",
        ],
        "practice": "Fill in: ___ book is on the table (I). / ___ dog runs fast (she).",
    },
    {
        "title": "Sentences Tell, Ask, Exclaim, Command",
        "concept": "Four kinds of sentences: statement (tell), question (ask), exclamation (exclaim), command (tell someone to do something).",
        "sentences": [
            "the sky is blue (statement)",
            "is the sky blue (question)",
            "what a blue sky (exclamation)",
            "look at the sky (command)",
            "the dog barks (statement)",
            "does the dog bark (question)",
            "what a loud bark (exclamation)",
            "stop barking (command)",
        ],
        "practice": "Identify each type: Go to bed. / It is raining. / How pretty! / Do you see?",
    },
    {
        "title": "Contractions with Not: Isn't, Aren't, Don't, Doesn't",
        "concept": "When we add not to a verb, we can make a contraction with an apostrophe.",
        "sentences": [
            "it is not cold -> it isn't cold",
            "they are not ready -> they aren't ready",
            "i do not like fish -> i don't like fish",
            "she does not eat meat -> she doesn't eat meat",
            "we are not coming -> we aren't coming",
            "he does not agree -> he doesn't agree",
        ],
        "practice": "Make contractions: is not -> ___ / do not -> ___ / are not -> ___",
    },
    {
        "title": "Contractions with Am, Is, Are, Have, Will",
        "concept": "Use contractions to join a pronoun with a verb.",
        "sentences": [
            "i am -> i'm",
            "you are -> you're",
            "he is -> he's",
            "she is -> she's",
            "it is -> it's",
            "we are -> we're",
            "they are -> they're",
            "i have -> i've",
            "we will -> we'll",
            "they will -> they'll",
        ],
        "practice": "Make contractions: I am happy -> I'm ___. / She is tall -> She's ___.",
    },
    {
        "title": "Was and Were for Past",
        "concept": "Use WAS with I, he, she, it. Use WERE with you, we, they.",
        "sentences": [
            "i was at home",
            "he was sick yesterday",
            "she was in class",
            "it was raining",
            "you were at the party",
            "we were happy",
            "they were at the park",
            "the dog was sleeping",
        ],
        "practice": "Choose was or were: I ___ tired. / They ___ at school.",
    },
    {
        "title": "Every Sentence Needs a Capital Letter",
        "concept": "Start every sentence with a capital letter, even after quotes.",
        "sentences": [
            "she said i am happy",
            "mom said go to bed",
            "teacher said we are learning",
            "dad said it is time to eat",
            "he asked where is the book",
            "she said i love reading",
        ],
        "practice": "Fix: she said the dog is big. / mom said time for bed.",
    },
    {
        "title": "Using Go and Went",
        "concept": "Go is present tense. Went is past tense.",
        "sentences": [
            "i go to school every day",
            "yesterday i went to the park",
            "we go to the library on fridays",
            "last week we went swimming",
            "she goes to dance class",
            "she went to a birthday party",
            "they go to church on sunday",
            "they went to a movie yesterday",
        ],
        "practice": "Choose go or went: Every day I ___ to school. Yesterday I ___ to the zoo.",
    },
    {
        "title": "Using Come and Came",
        "concept": "Come is present tense. Came is past tense.",
        "sentences": [
            "please come here now",
            "yesterday she came to my house",
            "we come to school by bus",
            "they came early today",
            "he comes to my house often",
            "he came to my house yesterday",
            "the bus comes at eight",
            "the bus came at eight yesterday",
        ],
        "practice": "Choose come or came: She ___ to school every day. Yesterday she ___ late.",
    },
    {
        "title": "See, Saw, Seen / Look, Looked / Watch, Watched",
        "concept": "Some verbs change completely in past tense.",
        "sentences": [
            "i see the bird",
            "i saw the bird yesterday",
            "she sees her friend",
            "she saw her friend at the park",
            "they look at the moon",
            "they looked at the stars last night",
            "we watch the game",
            "we watched the game on tv",
        ],
        "practice": "Fill in the blank: I ___ the movie yesterday. / I ___ movies every week.",
    },
]


def get_grammar_lessons(grade, full=True):
    """Get grammar lessons for a grade."""
    if grade == 1:
        return LESSONS_FULL_40 if full else LESSONS_BASELINE_10
    return []


def get_all_grammar_sentences(grade=1, full=True):
    """Extract all sentences from grammar lessons for a grade."""
    lessons = get_grammar_lessons(grade, full)
    sentences = []
    for lesson in lessons:
        sentences.extend(lesson["sentences"])
    return sentences


def get_lesson_by_title(title, grade=1, full=True):
    """Get a specific lesson by title."""
    lessons = get_grammar_lessons(grade, full)
    for lesson in lessons:
        if lesson["title"].lower() == title.lower():
            return lesson
    return None