"""
Color Corpus - Quantity (Label-Only)
High repetition of color words with minimal sensory context.
"""

QUANTITY_COLOR_CORPUS = [
    # Simple label repetition - 100 sentences
    "the red ball is red",
    "the blue ball is blue",
    "the green ball is green",
    "the yellow ball is yellow",
    "the orange ball is orange",
    "the purple ball is purple",
    "the black ball is black",
    "the white ball is white",
    "the brown ball is brown",
    "the pink ball is pink",

    "red is a color",
    "blue is a color",
    "green is a color",
    "yellow is a color",
    "orange is a color",
    "purple is a color",
    "black is a color",
    "white is a color",
    "brown is a color",
    "pink is a color",

    "i see red",
    "i see blue",
    "i see green",
    "i see yellow",
    "i see orange",
    "i see purple",
    "i see black",
    "i see white",
    "i see brown",
    "i see pink",

    "red red red",
    "blue blue blue",
    "green green green",
    "yellow yellow yellow",
    "orange orange orange",
    "purple purple purple",
    "black black black",
    "white white white",
    "brown brown brown",
    "pink pink pink",

    "the color is red",
    "the color is blue",
    "the color is green",
    "the color is yellow",
    "the color is orange",
    "the color is purple",
    "the color is black",
    "the color is white",
    "the color is brown",
    "the color is pink",

    "red things are red",
    "blue things are blue",
    "green things are green",
    "yellow things are yellow",
    "orange things are orange",
    "purple things are purple",
    "black things are black",
    "white things are white",
    "brown things are brown",
    "pink things are pink",

    "red and blue",
    "green and yellow",
    "orange and purple",
    "black and white",
    "brown and pink",
    "red and green",
    "blue and yellow",
    "orange and black",
    "purple and white",
    "pink and red",

    "red one blue two",
    "green three yellow four",
    "orange five purple six",
    "black seven white eight",
    "brown nine pink ten",
    "one red two blue",
    "three green four yellow",
    "five orange six purple",
    "seven black eight white",
    "nine brown ten pink",

    "red is first",
    "blue is second",
    "green is third",
    "yellow is fourth",
    "orange is fifth",
    "purple is sixth",
    "black is seventh",
    "white is eighth",
    "brown is ninth",
    "pink is tenth",

    "red goes here",
    "blue goes there",
    "green goes up",
    "yellow goes down",
    "orange goes left",
    "purple goes right",
    "black goes in",
    "white goes out",
    "brown goes near",
    "pink goes far",
]
