"""
1st Grade English Corpus - Comprehensive Curriculum Coverage

Based on Common Core 1st Grade standards.
Covers: Literacy (reading fluency/comprehension/writing), Mathematics
(addition/subtraction within 20, place value, measurement, geometry),
Science (weather patterns, plant/animal needs, light/sound), Social Studies
(communities, maps, history), Language development.
"""

ORIGINAL_CORPUS = [
    # === PHONICS: COMPLEX PATTERNS ===
    "air chair hair fair stair pair",
    "ear hear bear tear wear near",
    "are car far star bar jar",
    "ere here there where sphere",
    "eer deer beer cheer peer",
    "ure sure pure cure lure",
    "oor door floor poor roar",
    "our pour court four sour",
    "oi coin join boil point soil",
    "oy boy toy joy coy",
    "ou cloud loud proud found round",
    "ow cow how now brown clown",
    "aw saw paw law draw claw",
    "au haul fault vault launch",
    "ew grew flew crew blew",
    "oo moon spoon boot root shoot",
    "ui fruit juice suit bruise",
    "ue glue true blue clue",

    # === SIGHT WORDS (1st Grade Dolch) ===
    "after again an any as ask at ate away back be been both buy call came could does each eat even ever first found from give goes going had has her him his just keep know land large last let long look made make may many might most my never next off old once open or order other over own pick place pretty quite read right round said saw say set shall show six small start seven shall she show soon sound spell stop such take tell than that them then think this those thought through under until up upon us use very walk want warm was watch water way we well were what when which while wish with work would write you",

    # === READING FLUENCY ===
    "i can read a whole book by myself",
    "the story has a beginning middle and end",
    "i can tell you what happened in the story",
    "the main character is a brave little mouse",
    "the setting is a big forest with tall trees",
    "the problem is the mouse lost its home",
    "the solution is the mouse builds a new home",
    "i can read this sentence without stopping",
    "i can figure out new words when i read",
    "i can tell the difference between fiction and nonfiction",
    "fiction is a made up story",
    "nonfiction is about real things",
    "the author wrote this book",
    "the illustrator drew the pictures",
    "every paragraph has a main idea",

    # === WRITING ===
    "i can write a complete sentence",
    "a sentence starts with a capital letter",
    "a sentence ends with a period question mark or exclamation point",
    "i can write about something that happened to me",
    "i can write an opinion and give a reason",
    "i can write instructions that someone can follow",
    "i can use describing words in my writing",
    "i can use action words in my writing",
    "i can write a letter to a friend",
    "i can write a story with a problem and solution",
    "i can spell words i know by sounding them out",
    "i can use a dictionary to look up words",

    # === ADDITION WITHIN 20 ===
    "ten plus one equals eleven",
    "ten plus two equals twelve",
    "ten plus three equals thirteen",
    "ten plus four equals fourteen",
    "ten plus five equals fifteen",
    "ten plus six equals sixteen",
    "ten plus seven equals seventeen",
    "ten plus eight equals eighteen",
    "ten plus nine equals nineteen",
    "ten plus ten equals twenty",
    "nine plus two equals eleven",
    "eight plus three equals eleven",
    "seven plus four equals eleven",
    "six plus five equals eleven",
    "nine plus three equals twelve",
    "eight plus four equals twelve",
    "seven plus five equals twelve",
    "nine plus four equals thirteen",
    "eight plus five equals thirteen",
    "seven plus six equals thirteen",
    "nine plus five equals fourteen",
    "eight plus six equals fourteen",
    "nine plus six equals fifteen",
    "eight plus seven equals fifteen",
    "nine plus seven equals sixteen",
    "nine plus eight equals seventeen",
    "nine plus nine equals eighteen",

    # === SUBTRACTION WITHIN 20 ===
    "eleven minus one equals ten",
    "twelve minus two equals ten",
    "thirteen minus three equals ten",
    "fourteen minus four equals ten",
    "fifteen minus five equals ten",
    "sixteen minus six equals ten",
    "seventeen minus seven equals ten",
    "eighteen minus eight equals ten",
    "nineteen minus nine equals ten",
    "twenty minus ten equals ten",
    "eleven minus two equals nine",
    "twelve minus three equals nine",
    "thirteen minus four equals nine",
    "fourteen minus five equals nine",
    "fifteen minus six equals nine",
    "eleven minus three equals eight",
    "twelve minus four equals eight",
    "thirteen minus five equals eight",
    "fourteen minus six equals eight",
    "fifteen minus seven equals eight",

    # === PLACE VALUE TO 100 ===
    "twenty three is two tens and three ones",
    "thirty four is three tens and four ones",
    "forty five is four tens and five ones",
    "fifty six is five tens and six ones",
    "sixty seven is six tens and seven ones",
    "seventy eight is seven tens and eight ones",
    "eighty nine is eight tens and nine ones",
    "ninety two is nine tens and two ones",
    "one hundred is ten tens",
    "forty two is greater than thirty nine",
    "fifty five is less than sixty one",
    "seventy three equals seventy three",

    # === MEASUREMENT ===
    "measure the length of the desk in inches",
    "measure the length of the room in feet",
    "the pencil is six inches long",
    "the desk is three feet long",
    "the yardstick is three feet long",
    "the meter stick is one hundred centimeters long",
    "this book is longer than that book",
    "this book is shorter than that book",
    "this book is the same length as that book",
    "tell time to the hour and half hour",
    "it is three o clock",
    "it is half past three",

    # === MONEY ===
    "a penny is worth one cent",
    "a nickel is worth five cents",
    "a dime is worth ten cents",
    "a quarter is worth twenty five cents",
    "a dollar is worth one hundred cents",
    "a dollar is worth four quarters",
    "a dollar is worth ten dimes",
    "a dollar is worth twenty nickels",
    "a dollar is worth one hundred pennies",
    "i can count coins to find the total",
    "i have two dimes and a nickel that is twenty five cents",

    # === DATA & GRAPHS ===
    "we made a picture graph of our favorite fruits",
    "the bar graph shows how many pets each student has",
    "tally marks help us count by fives",
    "the survey asked what our favorite color is",
    "more students like blue than red",
    "the same number of students like green and yellow",
    "we organized our data into categories",
    "we interpreted the graph to answer questions",

    # === GEOMETRY (1st Grade) ===
    "a triangle has three sides and three corners",
    "a square has four equal sides and four corners",
    "a rectangle has four sides and four corners",
    "a circle is round and has no corners",
    "a hexagon has six sides",
    "i can put shapes together to make new shapes",
    "two triangles make a rectangle",
    "i can divide a circle into halves and fourths",
    "half of the pizza means two equal parts",
    "a fourth of the cake means four equal parts",

    # === SCIENCE: WEATHER PATTERNS ===
    "weather changes from day to day",
    "we observe and record weather patterns",
    "some days are sunny some are cloudy some are rainy",
    "seasons have different weather patterns",
    "spring is warm and rainy",
    "summer is hot and sunny",
    "fall is cool and windy",
    "winter is cold and snowy",
    "we dress differently for different weather",
    "we use a thermometer to measure temperature",

    # === SCIENCE: PLANT & ANIMAL NEEDS ===
    "plants need sunlight water and air to grow",
    "animals need food water air and shelter to live",
    "different animals live in different habitats",
    "a fish needs water to breathe",
    "a bird needs air to fly",
    "a plant turns sunlight into food",
    "animals eat plants or other animals",
    "baby animals look like their parents",
    "some animals change as they grow",
    "a caterpillar becomes a butterfly",

    # === SCIENCE: LIGHT & SOUND ===
    "light travels in straight lines",
    "light can be reflected like in a mirror",
    "light can pass through clear things",
    "light cannot pass through opaque things",
    "shadows are made when light is blocked",
    "sound is made when things vibrate",
    "loud sounds have big vibrations",
    "quiet sounds have small vibrations",
    "we can communicate using light and sound",
    "a flashlight sends a signal with light",
    "a drum sends a signal with sound",

    # === SOCIAL STUDIES: COMMUNITIES ===
    "a community is a place where people live and work together",
    "communities have rules to keep people safe",
    "people in communities have different jobs",
    "some people make goods like toys and clothes",
    "some people provide services like teaching and healing",
    "we buy goods and services with money",
    "people save money for things they need later",
    "communities have leaders who make decisions",
    "we vote to choose our leaders",

    # === SOCIAL STUDIES: MAPS ===
    "a map is a drawing of a place from above",
    "a map key tells what the symbols mean",
    "the compass rose shows north south east west",
    "my classroom is on the school map",
    "my neighborhood is on the town map",
    "continents are large areas of land",
    "oceans are large areas of water",
    "there are seven continents on earth",
    "there are five oceans on earth",

    # === SOCIAL STUDIES: HISTORY ===
    "history is the story of what happened in the past",
    "the past is before today",
    "the present is right now",
    "the future is what will happen later",
    "we learn about the past from old photos and stories",
    "important people in history changed the world",
    "holidays celebrate important events from the past",
    "our family has its own history",
    "our community has its own history",
    "our country has its own history",

    # === LANGUAGE: GRAMMAR ===
    "a noun is a person place or thing",
    "a verb is an action word",
    "an adjective describes a noun",
    "a pronoun takes the place of a noun",
    "i you he she it we they are pronouns",
    "run jump eat sleep are verbs",
    "big small red happy are adjectives",
    "cat school book apple are nouns",
    "sentences need a subject and a verb",
    "the subject tells who or what the sentence is about",
    "the verb tells what the subject does",

    # === LANGUAGE: COMPLEX SENTENCES ===
    "i went to the park because it was sunny",
    "although it was raining we played outside",
    "if you study hard you will do well",
    "while the teacher read we listened",
    "after we ate we cleaned up",
    "before we left we said goodbye",
    "since it was cold we wore coats",
    "unless you hurry we will be late",

    # === CHARACTER TRAITS ===
    "honesty means telling the truth",
    "respect means treating others kindly",
    "responsibility means doing what you should do",
    "courage means being brave even when scared",
    "kindness means being nice to others",
    "patience means waiting calmly",
    "perseverance means not giving up",
    "fairness means treating everyone equally",
    "gratitude means being thankful",
    "empathy means understanding how others feel",
]

VARIED_EXAMPLES = [
    # Phonics variations
    "the fair chair has a pair of stairs",
    "i hear the bear wear a tear",
    "the car is far from the star",
    "here is where the sphere is",
    "the deer cheer for the peer",
    "i am sure the pure cure will work",
    "the door on the floor has a poor roar",
    "pour the four sour courts",
    "i join the coin to boil the point",
    "the boy has a toy and joy",
    "the cloud is loud and proud",
    "the cow and clown are brown now",
    "i saw the paw draw with the law",
    "the fault in the vault will launch",
    "the crew flew and grew",
    "the moon has a spoon and boot",
    "fruit juice is sweet",
    "the glue is blue and true",

    # Reading fluency variations
    "the main character is a clever fox",
    "the setting is a small village",
    "the problem is the fox lost its way",
    "the solution is the fox followed the river home",
    "fiction is not real but it can teach us things",
    "nonfiction tells us facts about the world",
    "the author has a message for the reader",
    "the illustrator helps us see the story",
    "the main idea is the most important point",
    "details support the main idea",

    # Writing variations
    "i wrote about my trip to the zoo",
    "my opinion is that dogs are the best pets because they are loyal",
    "first wash your hands then dry them",
    "the big red ball bounced high",
    "the dog ran quickly across the yard",
    "dear friend i hope you are well",
    "once upon a time there was a little bird",
    "the bird could not fly so it learned to swim",

    # Addition variations
    "i have ten apples and get six more now i have sixteen",
    "nine children plus eight children equals seventeen children",
    "seven blocks plus seven blocks equals fourteen blocks",
    "six stars plus nine stars equals fifteen stars",
    "eight cars plus nine cars equals seventeen cars",

    # Subtraction variations
    "sixteen minus nine equals seven",
    "seventeen minus eight equals nine",
    "eighteen minus nine equals nine",
    "nineteen minus eight equals eleven",
    "twenty minus nine equals eleven",
    "i had fifteen candies and ate seven now i have eight",
    "twenty birds minus eleven birds equals nine birds",

    # Place value variations
    "twenty one is two tens and one one",
    "thirty seven is three tens and seven ones",
    "forty nine is four tens and nine ones",
    "fifty two is five tens and two ones",
    "sixty four is six tens and four ones",
    "seventy one is seven tens and one one",
    "eighty three is eight tens and three ones",
    "ninety five is nine tens and five ones",

    # Measurement variations
    "the table is four feet long",
    "the rug is five feet wide",
    "the window is three feet tall",
    "the hallway is ten feet long",
    "it is seven o clock time for school",
    "it is half past twelve time for lunch",
    "it is half past three time to go home",

    # Money variations
    "i have three dimes that is thirty cents",
    "i have two quarters that is fifty cents",
    "i have a quarter and two dimes that is forty five cents",
    "i have five nickels that is twenty five cents",
    "i count my coins one two three four five",

    # Weather variations
    "today is sunny and warm",
    "yesterday was cloudy and cool",
    "tomorrow might be rainy",
    "we recorded the weather for a whole month",
    "the pattern shows more sunny days than rainy days",
    "the temperature was seventy degrees today",

    # Plant/animal variations
    "the plant grew toward the sunlight",
    "without water the plant will wilt",
    "the dog needs fresh water every day",
    "the cat needs a warm place to sleep",
    "the frog starts as a tadpole in water",
    "the baby bird looks like its mother",

    # Light/sound variations
    "the mirror reflects the light",
    "the window lets light pass through",
    "the wall blocks the light and makes a shadow",
    "the guitar string vibrates to make sound",
    "the bell rings with a loud vibration",
    "the whisper has a quiet vibration",
    "the lighthouse sends light signals to ships",

    # Community variations
    "the baker makes bread for the community",
    "the nurse provides healthcare services",
    "the mechanic fixes cars for people",
    "the teacher provides education services",
    "i buy bread from the baker with money",
    "i save my allowance for a new toy",

    # History variations
    "my grandparents tell me stories about the past",
    "old photographs show us what life was like",
    "george washington was an important person in history",
    "our town was founded one hundred years ago",
    "independence day celebrates our country's history",

    # Grammar variations
    "the teacher is a person noun",
    "the school is a place noun",
    "the book is a thing noun",
    "the children run verb to the park",
    "the happy adjective cat sleeps",
    "she pronoun reads a book",
    "the big red dog runs fast",
    "the subject is the cat the verb is sleeps",

    # Complex sentence variations
    "i stayed inside because it was raining",
    "although i was tired i finished my homework",
    "if it snows we will build a snowman",
    "while mom cooked i set the table",
    "after school we played at the park",
    "before bed i read a story",
    "since it was hot we went swimming",
    "unless you practice you will not improve",

    # Character trait variations
    "i told the truth even when it was hard that is honesty",
    "i helped my classmate pick up their books that is kindness",
    "i finished my chores without being asked that is responsibility",
    "i stood up to the bully that is courage",
    "i waited my turn in line that is patience",
    "i kept trying even when the puzzle was hard that is perseverance",
    "i shared my snack with everyone that is fairness",
    "i said thank you for the gift that is gratitude",
    "i understood my friend was sad that is empathy",
    "i treated everyone the same way that is respect",
]

FULL_CORPUS = ORIGINAL_CORPUS + VARIED_EXAMPLES
