"""
Grammar Training Corpus - Subject-verb agreement, tense consistency, pronoun reference,
articles, prepositions, conjunctions, complex sentence structure
"""

ORIGINAL_CORPUS = [
    # Subject-verb agreement
    "he goes to school every day",
    "she goes to the store",
    "they go to the park",
    "we go to the movies",
    "i go to work",
    "it goes very fast",
    "the dog runs in the yard",
    "the dogs run in the yard",
    "a boy plays outside",
    "the boys play outside",
    "she has been working all day",
    "they have been working all day",
    "he has finished his homework",
    "they have finished their homework",
    "she was reading a book",
    "they were reading books",
    "the teacher explains the lesson",
    "the teachers explain the lessons",
    "my friend lives nearby",
    "my friends live nearby",

    # Tense consistency
    "yesterday she walked to school",
    "today she walks to school",
    "tomorrow she will walk to school",
    "she has walked to school every day this week",
    "she had walked to school before it started raining",
    "she will have walked to school by noon",
    "he was eating when the phone rang",
    "they were eating when the phone rang",
    "she had eaten before she left",
    "they had eaten before they left",
    "he will be studying all night",
    "they will be studying all night",
    "she has been studying for three hours",
    "they have been studying for three hours",

    # Pronoun reference
    "he gave the book to her",
    "she gave the book to him",
    "they gave the books to us",
    "we gave the books to them",
    "i gave the book to you",
    "you gave the book to me",
    "his book is on the table",
    "her book is on the table",
    "their books are on the table",
    "our books are on the table",
    "my book is on the table",
    "your book is on the table",
    "it is their responsibility",
    "it is our responsibility",
    "she did it herself",
    "they did it themselves",
    "he did it himself",
    "we did it ourselves",

    # Articles and determiners
    "a cat sat on the mat",
    "the cat sat on a mat",
    "an apple a day keeps the doctor away",
    "the apple is red",
    "a red apple fell from the tree",
    "some students passed the test",
    "all students passed the test",
    "each student passed the test",
    "every student passed the test",
    "many students passed the test",
    "few students passed the test",
    "several students passed the test",

    # Prepositions
    "the book is on the table",
    "the book is in the bag",
    "the book is under the table",
    "the book is beside the lamp",
    "the book is between the two chairs",
    "she walked through the door",
    "he jumped over the fence",
    "they ran across the field",
    "the bird flew above the clouds",
    "the fish swam below the surface",
    "we arrived at the station",
    "she traveled to paris",
    "he came from london",
    "they went into the room",
    "the cat climbed onto the roof",

    # Conjunctions and complex sentences
    "she studied hard because she wanted to pass",
    "he was tired but he kept working",
    "they arrived early so they got good seats",
    "if it rains we will stay inside",
    "although it was cold they went outside",
    "she not only sings but also dances",
    "either you come with us or you stay here",
    "neither the teacher nor the students were ready",
    "while she was cooking he was cleaning",
    "since you asked i will tell you",
    "unless you study you will not pass",
    "the book that i read was fascinating",
    "the man who called yesterday left a message",
    "the place where we met is closed",
    "the reason why she left is unknown",

    # Comparative and superlative
    "she is taller than her brother",
    "he is the tallest in the class",
    "this book is more interesting than that one",
    "this is the most interesting book i have read",
    "she runs faster than he does",
    "he runs the fastest of all",
    "the weather is better today",
    "today is the best day of the week",
    "she is smarter than her classmates",
    "he is the smartest student in school",
]

VARIED_EXAMPLES = [
    "she has been waiting for two hours",
    "they have been waiting for two hours",
    "he will have finished by tomorrow",
    "they will have finished by tomorrow",
    "the children were playing when it started to rain",
    "the child was playing when it started to rain",
    "her friends helped her with the project",
    "his friends helped him with the project",
    "each of the students has a different opinion",
    "none of the students has a different opinion",
    "the committee has reached its decision",
    "the committee members have reached their decision",
    "she looked at herself in the mirror",
    "he looked at himself in the mirror",
    "the report was written by the team",
    "the reports were written by the teams",
    "because she studied she passed the exam",
    "although he was tired he finished the work",
    "while they were traveling the car broke down",
    "if you practice you will improve",
]

FULL_CORPUS = ORIGINAL_CORPUS + VARIED_EXAMPLES
