"""
Kindergarten English Corpus - Comprehensive Curriculum Coverage

Based on Common Core Kindergarten standards and typical K curriculum frameworks
Covers: Literacy (reading/writing foundation), Mathematics (operations/place value),
Science (life cycles/habitats), Social Studies (maps/citizenship), Social-Emotional,
Physical/Arts, and Language development.
"""

ORIGINAL_CORPUS = [
    # === PHONICS: BLENDS & DIGRAPHS ===
    "bl blue black block blend",
    "cl clap clock cloud clean",
    "fl flag fly flip float",
    "gl glue glass globe glow",
    "pl plan play plum plate",
    "sl slide slow slip sleep",
    "br brush bread brick brown",
    "cr crab crack crop cream",
    "dr drum drop dress drive",
    "fr frog fruit frame fresh",
    "gr grass green grape grow",
    "pr print press prize proud",
    "tr train tree truck track",
    "sh ship shop fish wish",
    "ch chip chop chat lunch",
    "th this that with path",
    "wh what when where white",
    "ph phone photo graph dolphin",
    "ck back duck neck sock",
    "ng sing ring long wing",

    # === LONG VOWELS ===
    "a_e cake make take lake",
    "e_e me he she we",
    "i_e bike like time five",
    "o_e home bone rope note",
    "u_e cube tube mule rule",
    "ai rain train mail tail",
    "ay day play say stay",
    "ee see tree bee green",
    "ea eat tea sea leaf",
    "ie pie tie lie die",
    "oa boat coat road soap",
    "ow snow blow grow slow",
    "ue blue glue true cue",
    "ew chew new few grew",
    "igh night light right sight",
    "y fly my sky cry",

    # === SIGHT WORDS (Dolch Pre-Primer + Primer) ===
    "a and away big blue can come down find for funny",
    "go help here i in is it jump little look make me",
    "my not one play red run said see the three to two",
    "up we where yellow you all am are at ate be black",
    "brown but came did eat eight eleven four get has",
    "have how into like many must new nine no now on",
    "our out please pretty ran ride saw seven six so",
    "soon that there they this too under want was well",
    "went what who will with yes",

    # === READING SIMPLE SENTENCES ===
    "i can read this book",
    "the cat sat on the mat",
    "i see a big red ball",
    "the dog can run fast",
    "we like to play outside",
    "the sun is hot today",
    "i have a pet fish",
    "the bird can fly high",
    "my mom reads to me",
    "i can write my name",
    "the fish swims in water",
    "we go to school every day",
    "i like to draw pictures",
    "the tree has green leaves",
    "i can count to twenty",

    # === WRITING & LETTER FORMATION ===
    "i can write a b c d",
    "i can write my name",
    "i can write a sentence",
    "a is a capital letter",
    "a is a lowercase letter",
    "i write from left to right",
    "i start at the top",
    "i use a pencil to write",
    "i use paper to write on",
    "i can spell cat c a t",
    "i can spell dog d o g",
    "i can spell sun s u n",

    # === ADDITION ===
    "one plus one equals two",
    "one plus two equals three",
    "two plus two equals four",
    "three plus two equals five",
    "four plus one equals five",
    "five plus five equals ten",
    "three plus three equals six",
    "four plus four equals eight",
    "five plus one equals six",
    "six plus four equals ten",
    "seven plus three equals ten",
    "eight plus two equals ten",
    "nine plus one equals ten",
    "i have two apples and i get one more now i have three",
    "three birds and two more birds make five birds",

    # === SUBTRACTION ===
    "two minus one equals one",
    "three minus one equals two",
    "four minus two equals two",
    "five minus two equals three",
    "five minus three equals two",
    "ten minus five equals five",
    "six minus three equals three",
    "seven minus two equals five",
    "eight minus three equals five",
    "nine minus four equals five",
    "ten minus three equals seven",
    "i have five cookies and i eat two now i have three",
    "four birds fly away two stay how many are left",

    # === COUNTING TO 100 ===
    "i can count to one hundred",
    "ten twenty thirty forty fifty",
    "sixty seventy eighty ninety one hundred",
    "count by tens ten twenty thirty forty fifty sixty seventy eighty ninety one hundred",
    "count by fives five ten fifteen twenty twenty five thirty thirty five forty forty five fifty",
    "fifty five sixty sixty five seventy seventy five eighty eighty five ninety ninety five one hundred",
    "count by twos two four six eight ten twelve fourteen sixteen eighteen twenty",

    # === PLACE VALUE ===
    "ten ones make a ten",
    "eleven is ten and one",
    "twelve is ten and two",
    "thirteen is ten and three",
    "fourteen is ten and four",
    "fifteen is ten and five",
    "twenty is two tens",
    "thirty is three tens",
    "forty is four tens",
    "fifty is five tens",
    "one hundred is ten tens",

    # === MEASUREMENT ===
    "measure with a ruler",
    "measure with blocks",
    "measure with your hands",
    "this pencil is five blocks long",
    "this book is longer than that book",
    "this cup holds more water",
    "this cup holds less water",
    "weigh on a scale",
    "heavy things weigh more",
    "light things weigh less",

    # === SHAPES (2D & 3D) ===
    "circle square triangle rectangle",
    "oval star heart diamond",
    "pentagon hexagon octagon",
    "cube sphere cylinder cone",
    "a cube has six square faces",
    "a sphere is round like a ball",
    "a cylinder is round and tall",
    "a cone has a point on top",
    "a rectangle has four sides",
    "a triangle has three sides",

    # === PATTERNS (complex) ===
    "red blue green red blue green",
    "a b c a b c a b c",
    "one two three one two three",
    "big big small big big small",
    "circle square triangle circle square triangle",
    "what comes next in the pattern",
    "the pattern repeats",
    "i can make a pattern",
    "i can finish the pattern",

    # === GRAPHS & DATA ===
    "count and graph",
    "bar graph shows how many",
    "tally marks count by fives",
    "i tally how many red blocks",
    "the graph shows more blue than red",
    "the graph shows the same number",
    "survey means ask and count",
    "we surveyed our favorite color",

    # === LIFE CYCLES ===
    "a seed grows into a plant",
    "a caterpillar turns into a butterfly",
    "a tadpole turns into a frog",
    "an egg hatches into a chick",
    "a baby grows into an adult",
    "plants start as seeds",
    "butterflies start as eggs",
    "frogs start as eggs in water",
    "chickens start as eggs",
    "life cycles repeat",

    # === HABITATS ===
    "animals live in habitats",
    "fish live in water",
    "birds live in trees",
    "bears live in forests",
    "camels live in deserts",
    "penguins live in cold places",
    "rabbits live in burrows",
    "whales live in the ocean",
    "monkeys live in the jungle",
    "a habitat has food water and shelter",

    # === EARTH SCIENCE ===
    "rocks are hard",
    "soil is soft",
    "water flows downhill",
    "the earth has land and water",
    "mountains are high",
    "valleys are low",
    "rivers flow to the ocean",
    "the sun gives us light and heat",
    "the moon shines at night",
    "stars are far away",

    # === MAPS & GEOGRAPHY ===
    "a map shows places",
    "a globe shows the earth",
    "north south east west",
    "my town is on the map",
    "my state is on the map",
    "my country is on the map",
    "continents are big land areas",
    "oceans are big water areas",
    "there are seven continents",
    "there are five oceans",

    # === COMMUNITY & CITIZENSHIP ===
    "i am a citizen",
    "citizens follow rules",
    "citizens help each other",
    "we vote to choose leaders",
    "the president leads our country",
    "the mayor leads our town",
    "we recycle to help the earth",
    "we save water and energy",
    "we take care of our community",
    "flags represent countries",

    # === HOLIDAYS & TRADITIONS ===
    "we celebrate holidays",
    "new year is in january",
    "valentine day is in february",
    "we give thanks on thanksgiving",
    "we celebrate with family",
    "different people celebrate different holidays",
    "traditions are special things we do",
    "we share our traditions with others",

    # === SELF-REGULATION ===
    "i can calm my body",
    "i can take deep breaths",
    "i can count to ten when angry",
    "i can use my words not my hands",
    "i can wait for my turn",
    "i can try again when i fail",
    "i can ask for help",
    "i can solve problems",
    "i can share and take turns",
    "i can say how i feel",

    # === STORYTELLING ===
    "every story has a beginning middle and end",
    "the beginning tells who and where",
    "the middle tells what happens",
    "the end tells how it finishes",
    "characters are the people in a story",
    "the setting is where the story happens",
    "the problem is what goes wrong",
    "the solution is how it gets fixed",
    "i can tell a story",
    "i can retell a story i heard",

    # === QUESTIONING ===
    "who is in the story",
    "what happened first",
    "where did it happen",
    "when did it happen",
    "why did it happen",
    "how did it happen",
    "i can ask questions",
    "i can answer questions",
    "questions help me learn",

    # === VOCABULARY EXPANSION ===
    "enormous means very big",
    "tiny means very small",
    "rapid means very fast",
    "ancient means very old",
    "furious means very angry",
    "delighted means very happy",
    "exhausted means very tired",
    "frightened means very scared",
    "synonyms are words that mean the same",
    "antonyms are words that mean the opposite",
]

VARIED_EXAMPLES = [
    # Blend practice
    "the black cat sat on the block",
    "i clap my hands to the clock",
    "the flag flies in the wind",
    "i put glue on the glass",
    "we play a plan together",
    "i slide down slow",
    "i brush my brown hair",
    "the crab cracks the shell",
    "i drum on the dress",
    "the frog eats fruit",
    "the grass grows green",
    "i print a pretty picture",
    "the train goes on the track",
    "the ship sails to the shop",
    "i chat at lunch",
    "this is the path with the th sound",
    "what is white when it snows",
    "the phone has a photo",
    "the duck has a black neck",
    "i sing a long song",

    # Long vowel practice
    "i bake a cake",
    "he sees me",
    "i like to ride my bike",
    "i go home on the rope",
    "the cube is in the tube",
    "rain falls on the train",
    "i play all day",
    "i see a bee in the tree",
    "i eat tea leaves",
    "i tie a pie",
    "the boat has a coat",
    "snow blows slow",
    "the glue is blue",
    "i chew something new",
    "the light shines at night",
    "i fly my kite in the sky",

    # Addition variations
    "two plus three equals five",
    "one plus four equals five",
    "six plus two equals eight",
    "seven plus one equals eight",
    "five plus four equals nine",
    "six plus three equals nine",
    "eight plus one equals nine",
    "five plus five equals ten",
    "i have three blocks and get two more now i have five",
    "four apples plus three apples equals seven apples",
    "two cats plus five cats equals seven cats",

    # Subtraction variations
    "ten minus two equals eight",
    "ten minus four equals six",
    "nine minus three equals six",
    "eight minus four equals four",
    "seven minus three equals four",
    "six minus two equals four",
    "i have eight candies and eat three now i have five",
    "nine birds minus four birds equals five birds",

    # Counting variations
    "twenty one twenty two twenty three twenty four twenty five",
    "twenty six twenty seven twenty eight twenty nine thirty",
    "thirty one thirty two thirty three thirty four thirty five",
    "forty one forty two forty three forty four forty five",
    "fifty one fifty two fifty three fifty four fifty five",
    "sixty one sixty two sixty three sixty four sixty five",
    "seventy one seventy two seventy three seventy four seventy five",
    "eighty one eighty two eighty three eighty four eighty five",
    "ninety one ninety two ninety three ninety four ninety five ninety six ninety seven ninety eight ninety nine one hundred",

    # Life cycle variations
    "first the seed goes in soil then it sprouts then it grows then it flowers",
    "first the butterfly lays an egg then a caterpillar hatches then it makes a cocoon then a butterfly comes out",
    "first the frog lays eggs then tadpoles hatch then they grow legs then they become frogs",
    "first the hen lays an egg then the chick hatches then it grows feathers then it becomes a chicken",

    # Habitat variations
    "the ocean is a habitat for fish and whales",
    "the forest is a habitat for bears and deer",
    "the desert is a habitat for camels and lizards",
    "the arctic is a habitat for penguins and polar bears",
    "the jungle is a habitat for monkeys and snakes",
    "every animal needs a home with food and water",

    # Earth science variations
    "some rocks are smooth some rocks are rough",
    "soil has sand clay and rotting leaves",
    "water fills rivers lakes and oceans",
    "the earth spins around the sun",
    "the moon goes around the earth",
    "we see stars at night",

    # Map variations
    "the map key tells what symbols mean",
    "the compass shows north south east west",
    "my house is on the street map",
    "the park is north of my school",
    "the store is south of my house",
    "the library is east of the park",
    "the zoo is west of the school",

    # Storytelling variations
    "once upon a time there was a cat",
    "the cat lived in a big house",
    "one day the cat got lost",
    "the cat found its way home",
    "the end the cat was safe",
    "the character was a brave cat",
    "the setting was a big city",
    "the problem was the cat was lost",
    "the solution was the cat followed its nose home",

    # Self-regulation variations
    "when i am mad i stop and breathe",
    "when i am sad i talk to someone",
    "when i am scared i ask for help",
    "when i am frustrated i try again",
    "i can use my words to say i am upset",
    "i can walk away when i am angry",
    "i can count to ten before i react",

    # Questioning variations
    "who is the main character",
    "what was the problem",
    "where did the story happen",
    "when did it happen",
    "why did the character do that",
    "how did they solve the problem",
    "what would i do differently",

    # Vocabulary variations
    "huge is a synonym for enormous",
    "little is a synonym for tiny",
    "quick is a synonym for rapid",
    "old is a synonym for ancient",
    "mad is a synonym for furious",
    "glad is a synonym for delighted",
    "big and small are antonyms",
    "hot and cold are antonyms",
    "fast and slow are antonyms",
    "happy and sad are antonyms",
]

FULL_CORPUS = ORIGINAL_CORPUS + VARIED_EXAMPLES
