"""
2nd Grade English Corpus - Comprehensive Curriculum Coverage

Based on Common Core 2nd Grade standards.
Covers: Literacy (reading comprehension, fluency, writing), Mathematics
(addition/subtraction within 100, place value to 1000, measurement, money,
time, data), Science (ecosystems, Earth systems, engineering), Social Studies
(citizenship, economics, geography, history), Language development.
"""

ORIGINAL_CORPUS = [
    # === PHONICS: ADVANCED PATTERNS ===
    "tion action fraction nation station",
    "sion vision decision occasion",
    "ture picture nature future adventure",
    "cious delicious precious spacious",
    "tious cautious ambitious nutritious",
    "cian musician magician electrician",
    "able comfortable remarkable valuable",
    "ible possible terrible flexible",
    "ful beautiful wonderful careful helpful",
    "less endless fearless careless",
    "ness kindness darkness happiness",
    "ment movement excitement development",

    # === SIGHT WORDS (2nd Grade Dolch) ===
    "always around because been before best both bring build carry clean cut done draw drink eight else fall far full got grow hold hot if keep kind laugh light long much myself never only own people picture plant pull read ready real right round seem sense separate seven shall together try upon warm why wish would",

    # === READING COMPREHENSION ===
    "i can retell a story in my own words",
    "the main idea is what the story is mostly about",
    "details tell more about the main idea",
    "i can describe the characters in a story",
    "i can describe the setting of a story",
    "the plot is what happens in the story",
    "the beginning introduces the characters and setting",
    "the middle has the problem or challenge",
    "the end has the solution",
    "i can compare two versions of the same story",
    "i can explain how illustrations help tell the story",
    "i can find the lesson or moral of a story",
    "i can tell if a story is realistic or fantasy",
    "realistic fiction could really happen",
    "fantasy has things that cannot really happen",
    "i can read chapter books with many pages",
    "i can use context clues to figure out new words",

    # === WRITING ===
    "i can write a paragraph with a topic sentence",
    "i can write an opinion piece with reasons",
    "i can write a report about a topic i researched",
    "i can write a narrative with a sequence of events",
    "i can use transition words like first next then finally",
    "i can use linking words like because and so",
    "i can write a conclusion for my paragraph",
    "i can revise my writing to make it better",
    "i can edit my writing for spelling and punctuation",
    "i can use a thesaurus to find better words",
    "i can write a friendly letter with a greeting and closing",
    "i can write a thank you note",

    # === ADDITION & SUBTRACTION WITHIN 100 ===
    "twenty three plus fifteen equals thirty eight",
    "forty five plus twenty seven equals seventy two",
    "sixty eight minus thirty four equals thirty four",
    "ninety one minus forty six equals forty five",
    "fifty six plus thirty nine equals ninety five",
    "seventy two minus twenty eight equals forty four",
    "thirty four plus forty six equals eighty",
    "eighty five minus thirty seven equals forty eight",
    "i can add two digit numbers without regrouping",
    "i can add two digit numbers with regrouping",
    "i can subtract two digit numbers without regrouping",
    "i can subtract two digit numbers with regrouping",
    "i can solve word problems using addition and subtraction",
    "i can use mental math to add and subtract",
    "i can check my answer using the opposite operation",

    # === PLACE VALUE TO 1000 ===
    "one hundred is ten tens",
    "two hundred is twenty tens",
    "three hundred forty five is three hundreds four tens five ones",
    "five hundred sixty seven is five hundreds six tens seven ones",
    "seven hundred eighty nine is seven hundreds eight tens nine ones",
    "nine hundred ninety nine is nine hundreds nine tens nine ones",
    "one thousand is ten hundreds",
    "four hundred twelve is greater than three hundred ninety eight",
    "six hundred fifty is less than seven hundred one",
    "i can count by fives to one hundred",
    "i can count by tens to one thousand",
    "i can count by ones from any number",
    "i can read and write numbers to one thousand",

    # === MEASUREMENT ===
    "measure the length in centimeters",
    "measure the length in meters",
    "the table is one meter long",
    "the pencil is fifteen centimeters long",
    "estimate the length before measuring",
    "the string is longer than the pencil",
    "the book is shorter than the notebook",
    "tell time to the nearest five minutes",
    "it is three twenty five",
    "it is quarter past four",
    "it is quarter to five",
    "it is half past six",
    "a.m. is morning",
    "p.m. is afternoon and evening",
    "solve word problems involving time",
    "solve word problems involving money",

    # === MONEY ===
    "i have two dollars and twenty five cents",
    "three quarters equals seventy five cents",
    "five dimes equals fifty cents",
    "ten nickels equals fifty cents",
    "twenty five pennies equals twenty five cents",
    "i can make change from a dollar",
    "i can solve money word problems",
    "the toy costs three dollars and fifty cents",
    "i have five dollars i get one dollar fifty cents change",

    # === DATA & GRAPHS ===
    "we made a line plot to show our data",
    "the bar graph compares two categories",
    "we collected measurement data",
    "we organized data into a table",
    "the graph shows which category has the most",
    "the graph shows which category has the least",
    "we can answer questions using the graph",
    "the data shows a pattern",

    # === GEOMETRY ===
    "a triangle has three sides and three angles",
    "a quadrilateral has four sides",
    "a square is a type of quadrilateral",
    "a rectangle is a type of quadrilateral",
    "a rhombus is a type of quadrilateral",
    "a pentagon has five sides",
    "a hexagon has six sides",
    "i can partition a rectangle into equal squares",
    "i can divide a circle into equal shares",
    "halves thirds and fourths are equal shares",
    "two halves make one whole",
    "three thirds make one whole",
    "four fourths make one whole",

    # === SCIENCE: ECOSYSTEMS ===
    "plants and animals depend on each other",
    "plants make food from sunlight",
    "animals eat plants or other animals",
    "a food chain shows who eats whom",
    "decomposers break down dead plants and animals",
    "pollinators help plants make seeds",
    "bees butterflies and birds are pollinators",
    "animals live in habitats that meet their needs",
    "some animals hibernate in winter",
    "some animals migrate to warmer places",
    "camouflage helps animals hide",

    # === SCIENCE: EARTH SYSTEMS ===
    "earth has land and water",
    "mountains hills valleys and plains are landforms",
    "rivers lakes and oceans are bodies of water",
    "maps show where things are on earth",
    "earth changes slowly and quickly",
    "earthquakes change the land quickly",
    "erosion changes the land slowly",
    "water can move soil and rocks",
    "wind can move sand and soil",
    "fossils show us what lived long ago",

    # === SCIENCE: ENGINEERING ===
    "engineers design solutions to problems",
    "engineers test their designs",
    "engineers improve their designs",
    "i can design a solution to a problem",
    "i can test if my design works",
    "i can improve my design based on testing",
    "different materials have different properties",
    "some materials are strong some are flexible",
    "some materials are waterproof some absorb water",

    # === SOCIAL STUDIES: CITIZENSHIP ===
    "citizens have rights and responsibilities",
    "the constitution is the rule book for our country",
    "the bill of rights protects our freedoms",
    "freedom of speech means we can share our ideas",
    "freedom of religion means we can choose our beliefs",
    "voting is how we choose our leaders",
    "community leaders make decisions for everyone",
    "we can help our community by volunteering",
    "good citizens follow rules and help others",

    # === SOCIAL STUDIES: ECONOMICS ===
    "goods are things we can buy",
    "services are things people do for us",
    "producers make goods and provide services",
    "consumers buy goods and services",
    "supply is how much of something is available",
    "demand is how much people want something",
    "when demand is high prices go up",
    "when supply is high prices go down",
    "people save money in banks",
    "banks lend money to people and businesses",

    # === SOCIAL STUDIES: GEOGRAPHY ===
    "the united states has fifty states",
    "each state has its own capital city",
    "the capital of the united states is washington d c",
    "rivers lakes and mountains are natural features",
    "cities towns and roads are human made features",
    "people move to places for different reasons",
    "some places are cold some are warm",
    "some places are dry some are wet",
    "people adapt to where they live",

    # === SOCIAL STUDIES: HISTORY ===
    "historians study the past",
    "primary sources are from the time period",
    "secondary sources are written later",
    "timelines show when events happened",
    "important events shape our country",
    "important people change history",
    "we learn from mistakes of the past",
    "traditions are passed down through generations",
    "holidays celebrate important events",

    # === LANGUAGE: GRAMMAR ===
    "a common noun names any person place or thing",
    "a proper noun names a specific person place or thing",
    "proper nouns start with capital letters",
    "an action verb tells what the subject does",
    "a linking verb connects the subject to more information",
    "is am are was were are linking verbs",
    "an adverb tells how when or where",
    "quickly slowly yesterday here are adverbs",
    "a conjunction joins words or sentences",
    "and but or so are conjunctions",
    "an interjection shows strong feeling",
    "wow ouch hooray are interjections",

    # === LANGUAGE: SENTENCE STRUCTURE ===
    "a simple sentence has one complete thought",
    "a compound sentence has two complete thoughts",
    "use a comma before and but or in compound sentences",
    "the subject is who or what the sentence is about",
    "the predicate tells what the subject does or is",
    "sentences can be statements questions commands or exclamations",
    "a statement tells something",
    "a question asks something",
    "a command tells someone to do something",
    "an exclamation shows strong feeling",

    # === CHARACTER TRAITS & SEL ===
    "self control means managing your emotions",
    "perseverance means not giving up when things are hard",
    "responsibility means doing what you are supposed to do",
    "cooperation means working well with others",
    "respect means treating others the way you want to be treated",
    "honesty means telling the truth",
    "kindness means being nice to others",
    "empathy means understanding how others feel",
    "courage means doing the right thing even when it is hard",
    "gratitude means being thankful for what you have",
    "fairness means treating everyone equally",
    "patience means waiting calmly",
]

VARIED_EXAMPLES = [
    # Missing word coverage
    "a historian studies old documents",
    "a primary source is a letter from the past",
    "a timeline shows events in order",
    "a volunteer helps without getting paid",
    "a business sells goods to people",
    "a natural feature is a mountain or river",
    "the cost of the toy is three dollars",
    "we collect data for our science project",
    "we organize information into categories",
    "an angle is where two lines meet",
    "place value tells the value of each digit",
    "give a reason for your opinion",
    "i did research about dolphins",
    "self control means manage your emotion",
    "a hill is smaller than a mountain",
    "a plain is flat land",
    "a lake is surrounded by land",
    "an important event changed history",
    "the ocean is a large body of water",
    "a map shows where places are",
    "a rock is hard and solid",
    "the earth has land and water",
    "the river flows to the ocean",

    # Reading comprehension gap fixes
    "the character is brave in the story",
    "describe the character and the setting",
    "the setting is a place and time in the story",
    "the plot is what happens in the story",
    "the plot has a problem and a solution",
    "the brave character solves the problem",
    "the story has a character setting and plot",
    "what happens in the plot is the problem",
    "describe the brave character in the story",
    "the setting tells the place and time",
    "the lesson or moral of the story is to learn",
    "the fantasy story cannot really happen",
    "the realistic story could really happen",
    "fantasy cannot happen in real life",
    "realistic could happen in real life",
    "learn the lesson from the story moral",
    "a pronoun replaces he she they it",
    "tell time to the nearest minute on the clock",
    "sixty minutes in one hour",

    # Phonics variations
    "the action at the station caused a fraction",
    "the musician made a beautiful vision",
    "the picture of nature was an adventure",
    "the delicious cake was precious",
    "the cautious astronaut was ambitious",
    "the magician was also an electrician",
    "the comfortable chair was remarkable",
    "it was possible to be flexible",
    "the beautiful garden was wonderful",
    "the endless night was fearless",
    "the kindness brought happiness",
    "the movement caused excitement",

    # Reading comprehension variations
    "the main character was a brave firefighter",
    "the setting was a busy city in the future",
    "the problem was the bridge was broken",
    "the solution was to build a new bridge",
    "the lesson was teamwork makes the dream work",
    "the fantasy story had talking animals",
    "the realistic story was about a school day",
    "the illustrations showed the characters feelings",
    "i used context clues to understand the word",
    "the chapter book had twenty chapters",
    "the character in the story was brave and kind",
    "the setting of the story is a place and time",
    "the plot is what happens in the story",
    "the plot has a problem and a solution",
    "describe the character and the setting",

    # Writing variations
    "my topic sentence is dogs are the best pets",
    "dogs are loyal because they stay by your side",
    "first i woke up then i ate breakfast",
    "in conclusion i think everyone should read this book",
    "i revised my story to add more details",
    "i edited my spelling and punctuation",
    "dear grandma thank you for the birthday gift",
    "sincerely your grandson timmy",

    # Addition/subtraction variations
    "thirty seven plus forty two equals seventy nine",
    "fifty eight plus twenty nine equals eighty seven",
    "seventy three minus thirty five equals thirty eight",
    "ninety four minus fifty seven equals thirty seven",
    "i have forty five marbles and get twenty three more now i have sixty eight",
    "i had eighty two stickers and gave away thirty six now i have forty six",
    "i checked my subtraction by adding the answer back",
    "regroup means carry a ten to the next column",
    "regroup means borrow a ten from the next column",
    "check your answer by doing the opposite operation",
    "twenty is after nineteen and before twenty one",
    "twenty thirty forty fifty sixty seventy eighty ninety",

    # Place value variations
    "two hundred thirty four is two hundreds three tens four ones",
    "four hundred fifty six is four hundreds five tens six ones",
    "six hundred seventy eight is six hundreds seven tens eight ones",
    "eight hundred ninety is eight hundreds nine tens zero ones",
    "i can count by tens from two hundred to five hundred",
    "i can count by fives from zero to one hundred",

    # Measurement variations
    "the desk is eighty centimeters long",
    "the door is two meters tall",
    "the hallway is five meters long",
    "it is ten forty five a m time for recess",
    "it is three thirty p m time to go home",
    "it is quarter past seven time for dinner",

    # Money variations
    "the book costs four dollars and ninety nine cents",
    "i have three dollars and twenty five cents",
    "i bought a snack for one dollar fifty cents",
    "i had five dollars and got three dollars fifty cents back",
    "a dime is worth ten cents",
    "a nickel is worth five cents",
    "a penny is worth one cent",
    "two dimes and a nickel is twenty five cents",
    "the cost of the pencil is fifty cents",

    # Data variations
    "the line plot shows how tall the plants grew",
    "the bar graph shows favorite sports",
    "more students like soccer than basketball",
    "the same number of students like tennis and swimming",

    # Geometry variations
    "the quadrilateral has four equal sides",
    "the rhombus looks like a diamond",
    "i divided the pizza into four equal fourths",
    "i divided the cake into three equal thirds",
    "two fourths is the same as one half",

    # Ecosystem variations
    "the bee pollinated the flower",
    "the butterfly carried pollen from flower to flower",
    "the frog eats insects in the pond",
    "the owl hunts mice at night",
    "the bear hibernates in the cave during winter",
    "the birds migrate south for the winter",
    "the chameleon uses camouflage to hide",

    # Earth systems variations
    "the river carved a valley over many years",
    "the earthquake shook the ground",
    "the wind blew sand across the desert",
    "the flood moved rocks down the mountain",
    "the fossil showed a fish that lived millions of years ago",

    # Engineering variations
    "i designed a bridge that can hold weight",
    "i tested my bridge with books",
    "my bridge broke so i made it stronger",
    "wood is strong but paper is flexible",
    "plastic is waterproof but cloth absorbs water",

    # Citizenship variations
    "the first amendment protects free speech",
    "we voted for class president",
    "i volunteered at the food bank",
    "good citizens recycle and help neighbors",

    # Economics variations
    "the farmer produces vegetables",
    "the store sells goods to consumers",
    "when everyone wants the toy the price goes up",
    "when there are too many apples the price goes down",
    "my parents save money at the bank",

    # Geography variations
    "california is on the west coast",
    "new york is on the east coast",
    "the mississippi river runs through the middle",
    "people move to cities for jobs",
    "people in alaska wear warm clothes",
    "people in arizona stay cool in summer",

    # History variations
    "george washington was the first president",
    "abraham lincoln freed the slaves",
    "the declaration of independence was signed in seventeen seventy six",
    "my grandmother tells me stories about the past",
    "we celebrate independence day on july fourth",

    # Grammar variations
    "paris is a proper noun",
    "mr smith is a proper noun",
    "the dog runs action verb",
    "the sky is blue linking verb",
    "she ran quickly adverb tells how",
    "we will go tomorrow adverb tells when",
    "i want pizza but i will eat salad conjunction",
    "wow that was amazing interjection",

    # Sentence structure variations
    "the cat slept simple sentence",
    "the cat slept and the dog barked compound sentence",
    "the cat slept but the dog played compound sentence",
    "did you finish your homework question",
    "please close the door command",
    "what a beautiful day exclamation",

    # Character trait variations
    "i counted to ten when i was angry that is self control",
    "i kept trying even when the math was hard that is perseverance",
    "i did my homework without being asked that is responsibility",
    "i worked well with my partner that is cooperation",
    "i listened when others spoke that is respect",
    "i admitted i broke the window that is honesty",
    "i shared my lunch with someone who forgot theirs that is kindness",
    "i knew my friend was sad even though they smiled that is empathy",
    "i stood up for someone being bullied that is courage",
    "i wrote thank you notes to my teachers that is gratitude",
    "i gave everyone the same size piece that is fairness",
    "i waited quietly for my turn that is patience",
]

FULL_CORPUS = ORIGINAL_CORPUS + VARIED_EXAMPLES
