"""
10th Grade Corpus - aligned sentences
Covers: geometry, chemistry, US history, english 10, economics
"""

ORIGINAL_CORPUS = [
    # Math - Geometry
    "know precise definitions of angle circle perpendicular line parallel line and line segment",
    "represent transformations in the plane using diagrams and coordinate notation",
    "given a rectangle parallelogram trapezoid or regular polygon describe the rotations and reflections that carry it onto itself",
    "develop definitions of rotations reflections and translations in terms of angles and distance",
    "use geometric descriptions of rigid motions to transform figures and predict effects",
    "use the definition of congruence in terms of rigid motions to show two triangles are congruent",
    "explain how the criteria for triangle congruence asa sas and sss follow from rigid motions",
    "prove theorems about lines and angles including vertical angles and alternate interior angles",
    "prove theorems about triangles including the sum of interior angles and the midsegment theorem",
    "prove theorems about parallelograms including opposite sides and angles are congruent",
    "make formal geometric constructions with a compass straightedge and geometry software",
    "prove theorems about similarity using similarity transformations",
    "define trigonometric ratios sine cosine and tangent for acute angles using right triangles",
    "use trigonometric ratios and the pythagorean theorem to solve right triangles",
    "derive the formula for the area of a sector of a circle",
    "use coordinates to prove simple geometric theorems algebraically",
    "find the point on a directed line segment that partitions the segment in a given ratio",
    "derive the equation of a circle given its center and radius using the pythagorean theorem",

    # Science - Chemistry
    "atoms are the smallest unit of an element that retains its chemical properties",
    "the periodic table organizes elements by atomic number and recurring chemical properties",
    "electrons are arranged in energy levels around the nucleus of an atom",
    "chemical bonds form when atoms share or transfer electrons",
    "ionic bonds form between metals and nonmetals through electron transfer",
    "covalent bonds form when atoms share electrons to achieve stable electron configurations",
    "balance chemical equations to satisfy the law of conservation of mass",
    "the mole concept relates the mass of a substance to the number of particles",
    "calculate molar mass and convert between moles mass and number of particles",
    "classify chemical reactions as synthesis decomposition single replacement or double replacement",
    "stoichiometry uses balanced equations to calculate quantities of reactants and products",
    "the properties of acids and bases are determined by hydrogen ion concentration",
    "ph measures the acidity or basicity of a solution on a scale from zero to fourteen",
    "gases obey the gas laws relating pressure volume temperature and amount",
    "solutions are homogeneous mixtures of solutes dissolved in solvents",

    # Social Studies - US History
    "the progressive era brought reforms to address problems caused by industrialization",
    "muckrakers exposed corruption and social problems through investigative journalism",
    "the united states emerged as a world power after the spanish american war",
    "world war one began in europe and the united states joined in nineteen seventeen",
    "the nineteen twenties was a decade of economic prosperity and cultural change",
    "the great depression began with the stock market crash of nineteen twenty nine",
    "franklin roosevelts new deal created programs to provide relief recovery and reform",
    "world war two ended the great depression and transformed the american economy",
    "the cold war was a geopolitical struggle between the united states and the soviet union",
    "the civil rights movement fought to end racial segregation and discrimination",
    "the brown versus board of education decision declared school segregation unconstitutional",
    "the vietnam war divided the nation and led to widespread protests",
    "the watergate scandal led to president nixons resignation in nineteen seventy four",
    "the civil rights act of nineteen sixty four prohibited discrimination based on race and gender",
    "the fall of the berlin wall in nineteen eighty nine symbolized the end of the cold war",

    # English 10 - World Literature & Composition
    "analyze how an authors choices about structure create such effects as mystery and suspense",
    "determine a theme of a text and analyze how it is conveyed through details",
    "analyze how complex characters advance the plot and develop the theme",
    "analyze the impact of specific word choices on meaning and tone",
    "analyze how an author draws on and transforms source material from earlier works",
    "evaluate how effectively an author uses evidence and reasoning to support claims",
    "write arguments with precise claims and counterclaims using valid reasoning and evidence",
    "write informative explanatory texts to organize and analyze complex ideas",
    "use narrative techniques such as dialogue and pacing to develop experiences",
    "produce clear and coherent writing appropriate to task purpose and audience",
    "conduct research to answer a question or solve a problem using multiple sources",
    "analyze the structure of an argument including claim evidence warrants and rebuttals",
    "examine how historical context influences the themes of a literary work",
    "compare and contrast the treatment of similar themes in texts from different cultures",
    "analyze the use of satire irony and allegory in literary texts",

    # Economics
    "scarcity requires individuals and societies to make choices about resource allocation",
    "opportunity cost is the value of the next best alternative given up when making a choice",
    "supply and demand determine prices in a market economy",
    "the law of demand states that as price increases quantity demanded decreases",
    "the law of supply states that as price increases quantity supplied increases",
    "market equilibrium occurs where the quantity supplied equals the quantity demanded",
    "gross domestic product measures the total value of goods and services produced in a country",
    "inflation is the general increase in prices over time reducing purchasing power",
    "the federal reserve uses monetary policy to influence interest rates and the money supply",
    "fiscal policy involves government spending and taxation to influence the economy",
    "comparative advantage explains why countries benefit from international trade",
    "tariffs and quotas are trade barriers that restrict international commerce",
    "unemployment occurs when workers who are willing and able to work cannot find jobs",
    "the business cycle includes periods of expansion peak contraction and trough",
    "entrepreneurship drives innovation and economic growth in market economies",
]

VARIED_EXAMPLES = [
    "prove that the base angles of an isosceles triangle are congruent",
    "use the distance formula to find the length of a line segment",
    "the sine of an angle equals opposite over hypotenuse",
    "balance the equation h two plus o two yields h two o",
    "calculate the number of moles in thirty six grams of water",
    "a neutralization reaction produces water and a salt",
    "the progressive movement led to womens suffrage and labor reforms",
    "the dust bowl exacerbated the hardships of the great depression",
    "the marshall plan helped rebuild europe after world war two",
    "analyze the symbolism in the novel",
    "use transitions to connect ideas between paragraphs",
    "write a research paper with properly cited sources",
    "a shift in the demand curve reflects a change in consumer preferences",
    "elasticity measures how responsive quantity is to price changes",
    "the gini coefficient measures income inequality within a population",
    "congruent triangles have the same shape and size",
    "the periodic table has eighteen groups and seven periods",
    "the cold war led to the space race and nuclear arms race",
    "examine how the author uses foreshadowing to build tension",
    "central banks regulate the money supply to stabilize the economy",
]

FULL_CORPUS = ORIGINAL_CORPUS + VARIED_EXAMPLES
