"""
3rd Grade English Corpus - Comprehensive Curriculum Coverage

Based on Common Core 3rd Grade standards.
Covers: Literacy (reading fluency/comprehension/writing), Mathematics
(multiplication/division within 100, fractions, measurement, data, geometry),
Science (forces/interactions, weather, ecosystems, heredity), Social Studies
(government, economics, geography, history), Language development.
"""

ORIGINAL_CORPUS = [
    # === PHONICS: MULTI-SYLLABLE WORDS ===
    "tion action fraction nation station celebration",
    "sion vision decision occasion explosion",
    "ture picture nature future adventure temperature",
    "able comfortable remarkable valuable reliable",
    "ful beautiful wonderful careful helpful grateful",
    "ness kindness darkness happiness sadness",
    "ment movement excitement development improvement",
    "er teacher farmer baker runner faster",
    "est fastest tallest strongest biggest smallest",
    "un happy unhappy unfair untie undo",
    "re read reread rewrite rebuild return",
    "dis agree disagree appear disappear connect disconnect",

    # === SIGHT WORDS (3rd Grade Dolch) ===
    "about better bring carry clean cut done draw eight fall far five give good grow hold if keep kind laugh light long much myself never only own pick seven shall show six small start ten today together try upon warm why wish would",

    # === READING FLUENCY ===
    "i can read a chapter book with many pages",
    "i can read with expression and smooth pacing",
    "i can figure out the meaning of new words from context",
    "i can retell a story including the beginning middle and end",
    "i can describe how characters respond to challenges",
    "i can identify the theme or lesson of a story",
    "i can compare and contrast two stories by the same author",
    "i can read informational text about science and history",
    "i can find the main idea and supporting details",
    "i can use text features like headings and captions",
    "i can read aloud with accuracy and appropriate rate",
    "i can read silently for extended periods",

    # === WRITING ===
    "i can write an opinion essay with an introduction body and conclusion",
    "i can give three reasons to support my opinion",
    "i can write an informative report with facts and details",
    "i can write a narrative with dialogue and descriptive details",
    "i can use transition words to connect my ideas",
    "i can vary my sentence structure in my writing",
    "i can use a thesaurus to find synonyms",
    "i can edit my writing for grammar and spelling",
    "i can write a paragraph with a clear topic sentence",
    "i can use commas in addresses and dates",
    "i can write a dialogue with quotation marks",
    "i can revise my writing to add more details",

    # === MULTIPLICATION WITHIN 100 ===
    "two times three equals six",
    "two times four equals eight",
    "two times five equals ten",
    "two times six equals twelve",
    "two times seven equals fourteen",
    "two times eight equals sixteen",
    "two times nine equals eighteen",
    "two times ten equals twenty",
    "three times three equals nine",
    "three times four equals twelve",
    "three times five equals fifteen",
    "three times six equals eighteen",
    "three times seven equals twenty one",
    "three times eight equals twenty four",
    "three times nine equals twenty seven",
    "three times ten equals thirty",
    "four times four equals sixteen",
    "four times five equals twenty",
    "four times six equals twenty four",
    "four times seven equals twenty eight",
    "four times eight equals thirty two",
    "four times nine equals thirty six",
    "four times ten equals forty",
    "five times five equals twenty five",
    "five times six equals thirty",
    "five times seven equals thirty five",
    "five times eight equals forty",
    "five times nine equals forty five",
    "five times ten equals fifty",
    "six times six equals thirty six",
    "six times seven equals forty two",
    "six times eight equals forty eight",
    "six times nine equals fifty four",
    "six times ten equals sixty",
    "seven times seven equals forty nine",
    "seven times eight equals fifty six",
    "seven times nine equals sixty three",
    "seven times ten equals seventy",
    "eight times eight equals sixty four",
    "eight times nine equals seventy two",
    "eight times ten equals eighty",
    "nine times nine equals eighty one",
    "nine times ten equals ninety",
    "ten times ten equals one hundred",

    # === DIVISION WITHIN 100 ===
    "six divided by two equals three",
    "eight divided by two equals four",
    "ten divided by two equals five",
    "twelve divided by two equals six",
    "fourteen divided by two equals seven",
    "sixteen divided by two equals eight",
    "eighteen divided by two equals nine",
    "twenty divided by two equals ten",
    "twelve divided by three equals four",
    "fifteen divided by three equals five",
    "eighteen divided by three equals six",
    "twenty one divided by three equals seven",
    "twenty four divided by three equals eight",
    "twenty seven divided by three equals nine",
    "thirty divided by three equals ten",
    "twenty divided by four equals five",
    "twenty four divided by four equals six",
    "twenty eight divided by four equals seven",
    "thirty two divided by four equals eight",
    "thirty six divided by four equals nine",
    "forty divided by four equals ten",
    "thirty divided by five equals six",
    "thirty five divided by five equals seven",
    "forty divided by five equals eight",
    "forty five divided by five equals nine",
    "fifty divided by five equals ten",

    # === FRACTIONS ===
    "one half means one out of two equal parts",
    "one third means one out of three equal parts",
    "one fourth means one out of four equal parts",
    "two thirds means two out of three equal parts",
    "three fourths means three out of four equal parts",
    "a fraction has a numerator and a denominator",
    "the numerator tells how many parts we have",
    "the denominator tells how many equal parts in all",
    "one half is the same as two fourths",
    "two fourths is the same as one half",
    "i can compare fractions with the same denominator",
    "i can compare fractions with the same numerator",
    "one third is less than one half",
    "three fourths is greater than one half",

    # === MEASUREMENT & DATA ===
    "measure liquid volume in liters",
    "measure mass in grams and kilograms",
    "the apple weighs about one hundred grams",
    "the watermelon weighs about five kilograms",
    "the bottle holds one liter of water",
    "tell time to the nearest minute",
    "solve word problems involving time intervals",
    "the movie starts at three thirty and ends at five fifteen",
    "measure length to the nearest quarter inch",
    "make a line plot to show measurement data",
    "draw a scaled picture graph",
    "draw a scaled bar graph",
    "solve one step problems using graphs",

    # === GEOMETRY ===
    "a rectangle has four sides and four right angles",
    "a rhombus has four equal sides",
    "a square has four equal sides and four right angles",
    "a parallelogram has opposite sides that are parallel",
    "a trapezoid has one pair of parallel sides",
    "i can partition shapes into equal areas",
    "each part is a unit fraction of the whole",
    "area is the amount of space inside a shape",
    "perimeter is the distance around a shape",
    "find the area of a rectangle by multiplying length times width",
    "find the perimeter by adding all the sides",
    "the area of a rectangle is length times width",
    "the perimeter of a square is four times one side",

    # === SCIENCE: FORCES & INTERACTIONS ===
    "forces can cause objects to move",
    "pushes and pulls are forces",
    "stronger forces cause bigger changes in motion",
    "friction is a force that slows things down",
    "magnets can push or pull without touching",
    "magnetic force works through some materials",
    "opposite poles of magnets attract",
    "like poles of magnets repel",
    "gravity pulls objects toward the earth",
    "balanced forces mean no change in motion",
    "unbalanced forces cause a change in motion",

    # === SCIENCE: WEATHER & CLIMATE ===
    "weather is what happens day to day",
    "climate is the pattern of weather over many years",
    "some places have hot climates some have cold climates",
    "some places are dry some are wet",
    "seasons affect the weather in a region",
    "scientists record weather data to find patterns",
    "clouds form when water vapor cools",
    "rain falls when clouds get too heavy",
    "snow falls when the temperature is below freezing",
    "wind is moving air",
    "a thermometer measures temperature",
    "a rain gauge measures how much rain falls",

    # === SCIENCE: ECOSYSTEMS & HEREDITY ===
    "organisms live in environments that meet their needs",
    "when the environment changes some organisms survive some do not",
    "animals have traits inherited from their parents",
    "some traits are learned not inherited",
    "a caterpillar inherits the trait to become a butterfly",
    "a puppy inherits the trait to bark",
    "plants inherit traits like flower color and leaf shape",
    "variation means individuals in a group are different",
    "some variations help organisms survive",
    "fossils provide evidence of ancient environments",
    "many fossils are of organisms that no longer live on earth",

    # === SOCIAL STUDIES: GOVERNMENT ===
    "the united states has three branches of government",
    "the legislative branch makes laws",
    "the executive branch carries out laws",
    "the judicial branch interprets laws",
    "congress is part of the legislative branch",
    "the president is part of the executive branch",
    "the supreme court is part of the judicial branch",
    "the constitution is the supreme law of the land",
    "citizens have the right to free speech",
    "citizens have the responsibility to vote",
    "local government makes rules for our community",
    "state government makes rules for our state",
    "federal government makes rules for the country",

    # === SOCIAL STUDIES: ECONOMICS ===
    "resources are things people use to make goods and services",
    "natural resources come from nature",
    "human resources are the work people do",
    "capital resources are tools and machines",
    "specialization means people focus on one job",
    "trade allows people to get what they need",
    "import means to bring goods from another country",
    "export means to send goods to another country",
    "entrepreneurs start new businesses",
    "profit is the money a business earns",

    # === SOCIAL STUDIES: GEOGRAPHY ===
    "the seven continents are north america south america europe asia africa australia and antarctica",
    "the five oceans are pacific atlantic indian southern and arctic",
    "a hemisphere is half of the earth",
    "the equator divides the earth into northern and southern hemispheres",
    "the prime meridian divides the earth into eastern and western hemispheres",
    "a globe is a model of the earth",
    "a map scale shows the relationship between map distance and real distance",
    "latitude lines run east and west",
    "longitude lines run north and south",
    "physical maps show landforms and bodies of water",
    "political maps show borders and cities",

    # === SOCIAL STUDIES: HISTORY ===
    "ancient civilizations developed near rivers",
    "the egyptians built pyramids along the nile river",
    "the greeks developed democracy in athens",
    "the romans built roads and aqueducts",
    "explorers traveled to discover new lands",
    "columbus sailed across the atlantic ocean",
    "the industrial revolution changed how people worked",
    "inventions like the telegraph changed communication",
    "the civil rights movement fought for equality",
    "important leaders include martin luther king junior",

    # === LANGUAGE: GRAMMAR ===
    "a regular plural noun adds s or es",
    "irregular plural nouns change spelling like child to children",
    "a simple sentence has one independent clause",
    "a compound sentence has two independent clauses",
    "conjunctions like and but or connect clauses",
    "an adjective modifies a noun",
    "an adverb modifies a verb adjective or other adverb",
    "a preposition shows position or direction",
    "in on at under over are prepositions",
    "past tense verbs usually add ed",
    "present tense verbs show current action",
    "future tense verbs use will or going to",

    # === LANGUAGE: VOCABULARY ===
    "context clues help you figure out word meanings",
    "a prefix is added to the beginning of a word",
    "a suffix is added to the end of a word",
    "un means not like unhappy or unfair",
    "re means again like reread or rewrite",
    "ful means full of like helpful or careful",
    "less means without like careless or hopeless",
    "tion means the act of like action or celebration",
    "ment means the result of like movement or improvement",
    "synonyms are words with similar meanings",
    "antonyms are words with opposite meanings",
    "homophones sound the same but have different meanings",

    # === CHARACTER TRAITS & SEL ===
    "self awareness means knowing your emotions and strengths",
    "self management means controlling your impulses and emotions",
    "social awareness means understanding others perspectives",
    "relationship skills means communicating and cooperating",
    "responsible decision making means making safe and ethical choices",
    "resilience means bouncing back from challenges",
    "integrity means doing the right thing even when no one is watching",
    "tolerance means accepting differences in others",
    "leadership means guiding others in a positive way",
    "teamwork means working together toward a common goal",
]

VARIED_EXAMPLES = [
    # Missing word coverage
    "multiply means to add equal groups together",
    "divide means to split into equal groups",
    "times means multiply two times three",
    "divided by means split into groups",
    "the numerator is the top number",
    "the denominator is the bottom number",
    "area is measured in square units",
    "perimeter is measured in linear units",
    "push and pull are types of forces",
    "magnets attract and repel each other",
    "climate is weather over many years",
    "organisms survive or do not survive",
    "inherited traits come from parents",
    "the legislative branch makes the laws",
    "the executive branch carries out the laws",
    "the judicial branch interprets the laws",
    "natural resources come from the earth",
    "human resources are the work people do",
    "the equator divides the northern and southern hemispheres",
    "latitude and longitude help us find places",
    "ancient civilizations built pyramids and roads",
    "prefixes and suffixes change word meanings",
    "context clues help figure out new words",
    "self awareness means know your emotions",
    "resilience means bounce back from challenges",
    "integrity means do the right thing",
    "tolerance means accept differences",

    # Multiplication variations
    "i have three groups of four apples that is twelve apples",
    "five rows of six chairs equals thirty chairs",
    "seven packs of eight pencils equals fifty six pencils",
    "nine boxes of ten crayons equals ninety crayons",
    "multiply four by six to get twenty four",
    "eight times seven is the same as seven times eight",

    # Division variations
    "i share twenty cookies among four friends each gets five",
    "thirty six students divided into six groups means six per group",
    "forty two divided by seven equals six",
    "fifty four divided by nine equals six",
    "divide means split into equal groups",

    # Fraction variations
    "cut the pizza into four equal slices each is one fourth",
    "share the cake among three people each gets one third",
    "color two out of four parts that is two fourths",
    "one half is bigger than one fourth",
    "three fourths is bigger than one fourth",
    "the numerator is above the fraction bar",
    "the denominator is below the fraction bar",

    # Reading comprehension variations
    "the main character overcame a big challenge",
    "the theme of the story is friendship",
    "compare the two stories by the same author",
    "use the glossary to find word meanings",
    "the heading tells you what the section is about",
    "the caption explains the photograph",
    "read with expression to show how the character feels",

    # Writing variations
    "in my opinion recess should be longer because",
    "first next then finally are transition words",
    "the topic sentence tells what the paragraph is about",
    "john said i love reading said is a dialogue tag",
    "use a comma after the greeting in a letter",
    "i revised my essay to add more reasons",

    # Measurement variations
    "the movie lasted one hour and forty five minutes",
    "the bottle holds five hundred milliliters",
    "the dog weighs twenty kilograms",
    "the pencil is six and one quarter inches long",
    "the line plot shows the heights of all the plants",

    # Geometry variations
    "the rectangle is five units long and three units wide",
    "the area is fifteen square units",
    "the perimeter is sixteen units",
    "the square has sides of four units",
    "the area of the square is sixteen square units",
    "partition the rectangle into six equal parts",

    # Science variations
    "the magnet pulled the paperclip toward it",
    "friction between the tires and road slows the car",
    "gravity pulls the ball back to the ground",
    "the balanced forces kept the book still on the table",
    "the unbalanced force made the ball roll",
    "climate data shows this region gets lots of rain",
    "the cactus survives in the dry desert climate",
    "the puppy inherited its brown fur from its parents",
    "the bird learned to sing from its mother",
    "the fossil showed a fish that lived millions of years ago",

    # Government variations
    "congress makes laws for the whole country",
    "the president signs bills into law",
    "the supreme court decides if laws are fair",
    "the mayor leads the local government",
    "the governor leads the state government",

    # Economics variations
    "the farmer grows crops as a natural resource",
    "the carpenter uses tools as capital resources",
    "the baker specializes in making bread",
    "we import bananas from other countries",
    "we export cars to other countries",
    "the entrepreneur opened a new restaurant",

    # Geography variations
    "north america and south america are connected",
    "europe and asia are on the same landmass",
    "africa is south of europe",
    "australia is both a country and a continent",
    "antarctica is covered in ice",
    "the pacific ocean is the largest ocean",
    "the atlantic ocean separates america from europe",

    # History variations
    "the egyptians used the nile river for farming",
    "the greeks invented democracy",
    "the romans built strong roads",
    "explorers used ships to cross oceans",
    "the telegraph sent messages over wires",
    "martin luther king junior fought for equal rights",

    # Grammar variations
    "the children played in the park irregular plural",
    "she runs every morning present tense",
    "they will visit tomorrow future tense",
    "he walked to school past tense",
    "the book is on the table preposition",
    "she ran quickly adverb modifies verb",
    "the red car adjective modifies noun",

    # SEL variations
    "i know i am good at math that is self awareness",
    "i counted to ten when i was angry that is self management",
    "i understood why my friend was sad that is social awareness",
    "i listened when my partner spoke that is relationship skills",
    "i chose the safe option that is responsible decision making",
    "i tried again after failing that is resilience",
    "i told the truth even when it was hard that is integrity",
    "i accepted that my classmate was different that is tolerance",
    "i helped my team work together that is leadership",
    "we all worked toward the same goal that is teamwork",
]

FULL_CORPUS = ORIGINAL_CORPUS + VARIED_EXAMPLES
