"""
12th Grade Corpus - aligned sentences
Covers: calculus, statistics, environmental science, philosophy, comparative government
"""

ORIGINAL_CORPUS = [
    # Math - Calculus
    "the limit of a function describes the value the function approaches as the input approaches a point",
    "a function is continuous at a point if the limit equals the function value at that point",
    "the derivative of a function represents the instantaneous rate of change at a point",
    "use the definition of the derivative as the limit of the difference quotient",
    "apply the power rule product rule quotient rule and chain rule to find derivatives",
    "find the derivative of trigonometric exponential and logarithmic functions",
    "use derivatives to analyze the behavior of functions including increasing decreasing and concavity",
    "find absolute and relative extrema of functions on closed intervals",
    "apply the mean value theorem to relate average and instantaneous rates of change",
    "use lhopitals rule to evaluate limits of indeterminate forms",
    "the definite integral represents the net area under a curve over an interval",
    "the fundamental theorem of calculus connects differentiation and integration",
    "evaluate definite integrals using antiderivatives and the fundamental theorem",
    "use integration to find the area between curves and the volume of solids of revolution",
    "apply integration to solve problems involving motion work and accumulation",
    "find the antiderivative of a function using substitution and integration techniques",

    # Math - Statistics
    "distinguish between categorical and quantitative data and describe their distributions",
    "construct and interpret histograms box plots and stem and leaf plots",
    "calculate and interpret measures of center including mean median and mode",
    "calculate and interpret measures of spread including range variance and standard deviation",
    "the normal distribution is a symmetric bell shaped curve defined by its mean and standard deviation",
    "use the empirical rule to describe data within one two and three standard deviations of the mean",
    "calculate z scores to standardize values and compare observations from different distributions",
    "design a statistical study using random sampling and random assignment",
    "identify sources of bias in surveys experiments and observational studies",
    "construct and interpret confidence intervals for population proportions and means",
    "conduct hypothesis tests to evaluate claims about population parameters",
    "interpret p values and significance levels in the context of hypothesis testing",
    "analyze the relationship between two quantitative variables using scatter plots and correlation",
    "find and interpret the least squares regression line for bivariate data",
    "understand that correlation does not imply causation",
    "use chi square tests to analyze categorical data and test for independence",

    # Science - Environmental Science
    "ecology studies the interactions between organisms and their environment",
    "ecosystems consist of biotic and abiotic components that interact as a system",
    "biodiversity refers to the variety of life at genetic species and ecosystem levels",
    "population dynamics are influenced by birth rates death rates immigration and emigration",
    "carrying capacity is the maximum population size an environment can sustain",
    "biogeochemical cycles move nutrients such as carbon nitrogen and phosphorus through ecosystems",
    "climate change is caused by increased greenhouse gas concentrations in the atmosphere",
    "fossil fuel combustion releases carbon dioxide and contributes to global warming",
    "renewable energy sources include solar wind hydroelectric and geothermal power",
    "deforestation reduces biodiversity and contributes to climate change",
    "water pollution from agricultural industrial and urban sources threatens aquatic ecosystems",
    "the ozone layer protects earth from harmful ultraviolet radiation",
    "sustainable development meets present needs without compromising future generations",
    "natural selection and adaptation drive evolutionary change in populations",
    "human activities have accelerated the rate of species extinction significantly",
    "environmental policy balances economic development with ecological conservation",

    # Philosophy
    "epistemology is the branch of philosophy concerned with the nature and scope of knowledge",
    "metaphysics examines the fundamental nature of reality and existence",
    "ethics explores questions of right and wrong and moral obligation",
    "platos theory of forms posits that abstract ideals are more real than physical objects",
    "aristotle developed virtue ethics emphasizing character and the golden mean",
    "descartes method of doubt led to his famous conclusion i think therefore i am",
    "kant proposed the categorical imperative as a universal moral principle",
    "utilitarianism judges actions by their consequences seeking the greatest good for the greatest number",
    "existentialism emphasizes individual freedom choice and the creation of meaning",
    "social contract theory argues that political authority derives from the consent of the governed",
    "logic is the study of valid reasoning and argumentation",
    "a deductive argument is valid if the conclusion necessarily follows from the premises",
    "an inductive argument provides probable but not certain support for its conclusion",
    "philosophy of mind examines the relationship between consciousness and the physical brain",
    "the problem of free will questions whether human actions are determined or freely chosen",

    # Comparative Government
    "comparative politics analyzes and compares political systems across different countries",
    "democracy is a system of government in which power is held by the people through elections",
    "authoritarian regimes concentrate power in a single leader or small group without meaningful opposition",
    "totalitarian systems seek to control all aspects of public and private life",
    "parliamentary systems fuse executive and legislative power in the parliament",
    "presidential systems separate executive and legislative branches with distinct elections",
    "unitary states concentrate power in a central government while federal systems divide it",
    "political culture encompasses the attitudes beliefs and values that shape political behavior",
    "electoral systems including proportional representation and first past the post shape party systems",
    "civil society consists of voluntary organizations that operate independently of the state",
    "economic development influences the stability and quality of democratic institutions",
    "globalization affects national sovereignty and creates interdependence among states",
    "international organizations such as the united nations facilitate cooperation among nations",
    "constitutional frameworks define the structure and limits of governmental power",
    "political socialization is the process by which individuals acquire political beliefs and values",
]

VARIED_EXAMPLES = [
    "find the derivative of f of x equals x cubed plus two x squared minus five",
    "the integral of two x dx equals x squared plus c",
    "use the chain rule to differentiate sin of x squared",
    "approximately ninety five percent of data falls within two standard deviations of the mean",
    "a p value less than zero point zero five indicates statistical significance",
    "the correlation coefficient ranges from negative one to positive one",
    "the greenhouse effect traps heat in earths atmosphere",
    "acid rain is caused by sulfur dioxide and nitrogen oxide emissions",
    "platos allegory of the cave illustrates the nature of perception and reality",
    "nietzsche challenged traditional morality and proposed the concept of the uber mensch",
    "the united kingdom has a constitutional monarchy with a parliamentary system",
    "china is governed by a single party communist system",
    "evaluate the limit of sin x over x as x approaches zero",
    "the area under the curve is found by evaluating the definite integral",
    "a type one error occurs when a true null hypothesis is rejected",
    "the tragedy of the commons describes overuse of shared resources",
    "rawls theory of justice proposes the veil of ignorance as a thought experiment",
    "the european union represents a unique form of supranational governance",
    "find the volume of the solid formed by rotating y equals x squared around the x axis",
    "political legitimacy refers to the recognized right of a government to exercise authority",
]

FULL_CORPUS = ORIGINAL_CORPUS + VARIED_EXAMPLES
